import { Category, Question, Song } from './types';

// ==========================================
// 🎵 Musical Chairs Songs (Updated & Expanded)
// ==========================================
export const SONGS_DB: Song[] = [
  {
    id: 'song_13',
    title: 'محمود التركي - يمة حميد (حصرياً) _ Mahmood Al Turky - Yema Hamid (Exclusive) _ 2015',
    url: 'https://res.cloudinary.com/dwskvuxo5/video/upload/v1770922345/%D9%8A%D9%85%D8%A9-%D8%AD%D9%85%D9%8A%D8%AF-%D8%AD%D8%B5%D8%B1%D9%8A%D8%A7--mahmood-al-turky---yema-hamid-exclusive--2015_ngw46e.mp3'
  },
  {
    id: 'song_1',
    title: 'اغنية سيستم واحد _ ( حصرياً خلودي 25 ) _ باور',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059642/%D8%A7%D8%BA%D9%86%D9%8A%D8%A9_%D8%B3%D9%8A%D8%B3%D8%AA%D9%85_%D9%88%D8%A7%D8%AD%D8%AF___%D8%AD%D8%B5%D8%B1%D9%8A%D8%A7%D9%8B_%D8%AE%D9%84%D9%88%D8%AF%D9%8A_25___%D8%A8%D8%A7%D9%88%D8%B1_rpapsi.mp3'
  },
  {
    id: 'song_2',
    title: 'Fadl Shaker ... Fen Layalik _ فضل شاكر ... فين لياليك',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059580/Fadl_Shaker_..._Fen_Layalik___%D9%81%D8%B6%D9%84_%D8%B4%D8%A7%D9%83%D8%B1_..._%D9%81%D9%8A%D9%86_%D9%84%D9%8A%D8%A7%D9%84%D9%8A%D9%83_bhaogu.mp3'
  },
  {
    id: 'song_3',
    title: 'فهد بن فصلا - لايهمك (حصرياً) _ 2025',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059562/%D9%81%D9%87%D8%AF_%D8%A8%D9%86_%D9%81%D8%B5%D9%84%D8%A7_-_%D9%84%D8%A7%D9%8A%D9%87%D9%85%D9%83_%D8%AD%D8%B5%D8%B1%D9%8A%D8%A7%D9%8B___2025_wo5kym.mp3'
  },
  {
    id: 'song_4',
    title: 'شيلة_يالله_يالي_بك_نعز_ونهتدياداء_جفران_المري',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059552/%D8%B4%D9%8A%D9%84%D8%A9_%D9%82%D8%AD%D8%B7%D8%A7%D9%86_%D9%82%D8%AD%D8%B7%D8%A7%D9%86_%D8%A7%D9%84%D9%88%D9%81%D8%A7%D8%A1_enqk9w.mp3'
  },
  {
    id: 'song_5',
    title: 'شيلة قحطان قحطان الوفاء',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059549/%D8%B4%D9%8A%D9%84%D8%A9_%D9%82%D8%AD%D8%B7%D8%A7%D9%86_%D9%82%D8%AD%D8%B7%D8%A7%D9%86_%D8%A7%D9%84%D9%88%D9%81%D8%A7%D8%A1_enqk9w.mp3'
  },
  {
    id: 'song_6',
    title: 'رعد و ميثاق السامرائي - اذيه ( فيديو كليب )_2017',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059549/%D8%B1%D8%B9%D8%AF_%D9%88_%D9%85%D9%8A%D8%AB%D8%A7%D9%82_%D8%A7%D9%84%D8%B3%D8%A7%D9%85%D8%B1%D8%A7%D9%8A%D9%94%D9%8A_-_%D8%A7%D8%B0%D9%8A%D9%87_%D9%81%D9%8A%D8%AF%D9%8A%D9%88_%D9%83%D9%84%D9%8A%D8%A8__2017_j1kcjr.mp3'
  },
  {
    id: 'song_7',
    title: 'هيفاء-وهبيفاكرني',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059547/%D8%B9%D9%8A%D8%A7%D9%84_%D9%85%D8%B6%D9%8A%D9%85_xzgrxz.mp3'
  },
  {
    id: 'song_8',
    title: 'تركي العلي - سبحانه مغير الاحوال (جديد 2011)',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059544/%D8%AA%D8%B1%D9%83%D9%8A_%D8%A7%D9%84%D8%B9%D9%84%D9%8A_-_%D8%B3%D8%A8%D8%AD%D8%A9%D9%86%D9%87_%D9%85%D8%BA%D9%8A%D8%B1_%D8%A7%D9%84%D8%A7%D8%AD%D9%88%D8%A7%D9%84_%D8%AC%D8%AF%D9%8A%D8%AF_2011_mxz6wr.mp3'
  },
  {
    id: 'song_9',
    title: 'محمد عبده - ألا وا شيب عيني - فبراير 2005',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059540/%D9%85%D8%AD%D9%85%D8%AF_%D8%B9%D8%A8%D8%AF%D9%87_-_%D8%A3%D9%84%D8%A7_%D9%88%D8%A7_%D8%B4%D9%8A%D8%A8_%D8%B9%D9%8A%D9%86%D9%8A_-_%D9%81%D8%A8%D8%B1%D8%A7%D9%8A%D8%B1_2005_-_HD_tdwb97.mp3'
  },
  {
    id: 'song_10',
    title: 'محمد عبده _ توصيني على الكتمان .. وتبغى حبنا ما يبان !',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059538/%D9%85%D8%AD%D9%85%D8%AF_%D8%B9%D8%A8%D8%AF%D9%87___%D8%AA%D9%88%D8%B5%D9%8A%D9%86%D9%8A_%D8%B9%D9%84%D9%89_%D8%A7%D9%84%D9%83%D8%AA%D9%85%D8%A7%D9%86_.._%D9%88%D8%AA%D8%A8%D8%BA%D9%89_%D8%AD%D8%A8%D9%86%D8%A7_%D9%85%D8%A7_%D9%8A%D8%A8%D8%A7%D9%86_HQ_axy5ye.mp3'
  },
  {
    id: 'song_11',
    title: 'Nancy Ajram - Ya Albo_ (Official Music Video) نانسي عجرم - يا قلبو',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059538/Nancy_Ajram_-_Ya_Albo__Official_Music_Video_%D9%86%D8%A7%D9%86%D8%B3%D9%8A_%D8%B9%D8%AC%D8%B1%D9%85_-_%D9%8A%D8%A7_%D9%82%D9%84%D8%A8%D9%88___maxkpx.mp3'
  },
  {
    id: 'song_12',
    title: 'VIDRADO EM VOCE - DJ GUUGA e MC LIVINHO (Pode Sentار)',
    url: 'https://res.cloudinary.com/dekkgp3rb/video/upload/v1770059537/VIDRADO_EM_VOCE_-_DJ_GUUGA_e_MC_LIVINHO_Pode_Sentar_omzkgz.mp3'
  },
];

// ==========================================
// 🗺️ Maps / Layouts for Musical Chairs
// ==========================================
export const CHAIR_MAPS = [
  { id: 'circle', label: 'ساحة الدائرة', icon: '⭕', description: 'التصميم الكلاسيكي المتوازن' },
  { id: 'square', label: 'القلعة المربعة', icon: '🟦', description: 'توزيع زوايا استراتيجي' },
  { id: 'triangle', label: 'مثلث القمة', icon: '🔺', description: 'تحدي الحواف الضيقة' },
];

// ==========================================
// 16 Categories (Refined with Premium Images & Sequential IDs)
// ==========================================
export const CATEGORIES: Category[] = [
  { id: 'ramadan', label: 'فوازير رمضان', icon: '🌙', image: ['https://images.unsplash.com/photo-1596627008794-d2e7ff2b415a?q=80&w=800', 'https://i.ibb.co/k6mHccgc/content.png'] },
  { id: 'movies', label: 'أفلام ومسلسلات', icon: '🎬', image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800' },
  { id: 'cars', label: 'عالم السيارات', icon: '🏎️', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=800' },
  { id: 'islamic', label: 'إسلاميات', icon: '🕌', image: 'https://i.ibb.co/5XT1YWXs/sharjah-mosque-04.jpg' },
  { id: 'football', label: 'كرة قدم', icon: '⚽', image: 'https://i.ibb.co/TM5N1NsD/image.png' },
  { id: 'animals', label: 'عالم الحيوان', icon: '🦁', image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=80&w=800' },
  { id: 'gaming', label: 'ألعاب فيديو', icon: '🎮', image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=800' },
  { id: 'anime', label: 'أنمي ومانجا', icon: '⛩️', image: 'https://i.ibb.co/3mbBNPQ0/Whats-App-Image-2022-11-05-at-3-19-11-PM.webp' },
  { id: 'history', label: 'تاريخ', icon: '📜', image: 'https://i.ibb.co/N27nXjP4/974b9884-9bd0-4977-99a0-697adbb8a71e.jpg' },
  { id: 'science', label: 'علوم', icon: '🧬', image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=800' },
  { id: 'saudi', label: 'يوم التأسيس', icon: '🇸🇦', image: 'https://i.ibb.co/gFgkXdH4/arrdah.jpg' },
  { id: 'technology', label: 'تكنولوجيا', icon: '💻', image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=800' },
  { id: 'music', label: 'موسيقى وفنون', icon: '🎨', image: 'https://i.ibb.co/S42vXGfD/659b633c73fa75b9f907409caacd2cab-XL.jpg' },
  { id: 'geography', label: 'جغرافيا وسفر', icon: '🌍', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800' },
  { id: 'food', label: 'طعام وطبخ', icon: '🍳', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800' },
  { id: 'people', label: 'شخصيات عالمية', icon: '👤', image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=800' },
];

// ==========================================
// QUESTIONS DATABASE - (40 for Ramadan, 30 for others)
// ==========================================
export const QUESTIONS_DB: Question[] = [
  // فوازير رمضان (40 سؤال)
  { id: 1, category: 'ramadan', text: 'من هو الصحابي الذي لُقب بـ "ذو النورين"؟', options: ['ابو بكر', 'عمر بن الخطاب', 'عثمان بن عفان', 'علي بن ابي طالب'], correctIndex: 2 },
  { id: 2, category: 'ramadan', text: 'ما هو الغاز الأكثر تواواجداً في الكون بنسبة 75%؟', options: ['الاكسجين', 'النيتروجين', 'الهيدروجين', 'الهيليوم'], correctIndex: 2 },
  { id: 3, category: 'ramadan', text: 'ما هي السورة التي تسمى "قلب القران"؟', options: ['البقرة', 'يس', 'الفاتحة', 'الرحمن'], correctIndex: 1 },
  { id: 4, category: 'ramadan', text: 'في اي مدينة يوجد مقر محكمة العدل الدولية؟', options: ['جنيف', 'لندن', 'لاهاي', 'نيويورك'], correctIndex: 2 },
  { id: 5, category: 'ramadan', text: 'من هو القائد المسلم الذي فتح بلاد الاندلس؟', options: ['عقبة بن نافع', 'طارق بن زياد', 'قتيبة بن مسلم', 'موسى بن نصير'], correctIndex: 1 },
  { id: 6, category: 'ramadan', text: 'ما هو المعدن السائل الوحيد في درجة حرارة الغرفة؟', options: ['الرصاص', 'النحاس', 'الزئبق', 'القصدير'], correctIndex: 2 },
  { id: 7, category: 'ramadan', text: 'من هو النبي الذي لُقب بـ "كليم الله"؟', options: ['ابراهيم', 'عيسى', 'موسى', 'نوح'], correctIndex: 2 },
  { id: 8, category: 'ramadan', text: 'ما هي الدولة التي تمتلك أكبر عدد من الجزر في العالم؟', options: ['اندونيسيا', 'الفلبين', 'السويد', 'اليونان'], correctIndex: 2 },
  { id: 9, category: 'ramadan', text: 'كم عدد عظام جسم الانسان البالغ؟', options: ['206', '210', '300', '195'], correctIndex: 0 },
  { id: 10, category: 'ramadan', text: 'من هو الصحابي الذي اهتز لموته عرش الرحمن؟', options: ['حمزة بن عبد المطلب', 'سعد بن معاذ', 'جعفر بن ابي طالب', 'زيد بن حارثة'], correctIndex: 1 },
  { id: 11, category: 'ramadan', text: 'ما هو أعمق خندق مائي في العالم؟', options: ['خندق جاوا', 'خندق ماريانا', 'خندق تونجا', 'خندق الفلبين'], correctIndex: 1 },
  { id: 12, category: 'ramadan', text: 'من هي اخر من توفي من زوجات الرسول؟', options: ['عائشة', 'ام سلمة', 'ميمونة', 'سودة'], correctIndex: 1 },
  { id: 13, category: 'ramadan', text: 'ما هو العنصر الكيميائي الذي يرمز له بالرمز (Au)؟', options: ['الفضة', 'الذهب', 'النحاس', 'الحديد'], correctIndex: 1 },
  { id: 14, category: 'ramadan', text: 'في اي عام وقعت معركة حطين؟', options: ['583 هـ', '600 هـ', '450 هـ', '512 هـ'], correctIndex: 0 },
  { id: 15, category: 'ramadan', text: 'ما هو الكوكب الذي يلقب بـ "الكوكب الاحمر"؟', options: ['الزهرة', 'المشتري', 'المريخ', 'عطارد'], correctIndex: 2 },
  { id: 16, category: 'ramadan', text: 'من هو اول من قدر الساعات الاثنى عشر؟', options: ['ابراهيم', 'نوح', 'ادم', 'عيسى'], correctIndex: 1 },
  { id: 17, category: 'ramadan', text: 'ما هو اطول نهر في قارة اوروبا؟', options: ['الدانوب', 'الراين', 'الفولجا', 'التايمز'], correctIndex: 2 },
  { id: 18, category: 'ramadan', text: 'اين يتم انتاج خلايا الدم الحمراء في الجسم؟', options: ['القلب', 'الكبد', 'نخاع العظم', 'الكلى'], correctIndex: 2 },
  { id: 19, category: 'ramadan', text: 'ما هو الاسم الذي اطلق على مكة في القران غير "مكة"؟', options: ['طيبة', 'بكة', 'يثرب', 'الفسطاط'], correctIndex: 1 },
  { id: 20, category: 'ramadan', text: 'من هو العالم الذي اكتشف الدورة الدموية الصغرى؟', options: ['ابن سينا', 'ابن النفيس', 'الرازي', 'الفارابي'], correctIndex: 1 },
  { id: 21, category: 'ramadan', text: 'ما هي عاصمة كندا؟', options: ['تورنتو', 'مونتريال', 'اوتاوا', 'فانكوفر'], correctIndex: 2 },
  { id: 22, category: 'ramadan', text: 'من هو الصحابي الذي لُقب بـ "حبر الامة"؟', options: ['عبد الله بن عمر', 'عبد الله بن عباس', 'معاذ بن جبل', 'ابو هريرة'], correctIndex: 1 },
  { id: 23, category: 'ramadan', text: 'ما هو الغاز الذي يستخدمه النبات في عملية البناء الضوئي؟', options: ['الاكسجين', 'الهيدروجين', 'ثاني اكسيد الكربون', 'النيتروجين'], correctIndex: 2 },
  { id: 24, category: 'ramadan', text: 'ما هي السورة التي بدأت باسم نوع من الفاكهة؟', options: ['النمل', 'التين', 'النحل', 'النجم'], correctIndex: 1 },
  { id: 25, category: 'ramadan', text: 'من هو مخترع المصباح الكهربائي؟', options: ['تسلا', 'اديسون', 'جراهام بيل', 'نيوتن'], correctIndex: 1 },
  { id: 26, category: 'ramadan', text: 'كم عدد القلوب التي يمتلكها الاخطبوط؟', options: ['قلب واحد', 'قلبين', 'ثلاثة قلوب', 'اربعة قلوب'], correctIndex: 2 },
  { id: 27, category: 'ramadan', text: 'في اي سنة ميلادية سقطت الدولة الاندلسية (غرناطة)؟', options: ['1492م', '1500م', '1200م', '1453م'], correctIndex: 0 },
  { id: 28, category: 'ramadan', text: 'ما هي اصغر قارة في العالم من حيث المساحة؟', options: ['اوروبا', 'افريقيا', 'استراليا', 'امريكا الجنوبية'], correctIndex: 2 },
  { id: 29, category: 'ramadan', text: 'من هو الصحابي الذي لُقب بـ "امين السر" للرسول؟', options: ['بلال بن رباح', 'حذيفة بن اليمان', 'خالد بن الوليد', 'الزبير بن العوام'], correctIndex: 1 },
  { id: 30, category: 'ramadan', text: 'ما هي اقوى عضلة في جسم الانسان (بالنسبة لحجمها)؟', options: ['عضلة القلب', 'عضلة الفخذ', 'عضلة الفك', 'عضلة اللسان'], correctIndex: 2 },
  { id: 31, category: 'ramadan', text: 'ما هي السورة التي لا تبدأ بالبسملة؟', options: ['الكهف', 'التوبة', 'النور', 'يس'], correctIndex: 1 },
  { id: 32, category: 'ramadan', text: 'ما هو الكوكب الاكثر حرارة في المجموعة الشمسية؟', options: ['عطارد', 'الزهرة', 'المريخ', 'المشتري'], correctIndex: 1 },
  { id: 33, category: 'ramadan', text: 'من هو النبي الذي ارسل الى قوم ثمود؟', options: ['هود', 'صالح', 'شعيب', 'لوط'], correctIndex: 1 },
  { id: 34, category: 'ramadan', text: 'ما هي الدولة التي تسمى "ارض الشمس المشرقة"؟', options: ['الصين', 'كوريا', 'اليابان', 'تايلاند'], correctIndex: 2 },
  { id: 35, category: 'ramadan', text: 'من هو الصحابي الذي قاد المسلمين في معركة القادسية؟', options: ['خالد بن الوليد', 'سعد بن ابي وقاص', 'ابو عبيدة', 'عمرو بن العاص'], correctIndex: 1 },
  { id: 36, category: 'ramadan', text: 'ما هو العلم الذي يدرس طبقات الارض؟', options: ['البيولوجيا', 'الجيولوجيا', 'السيزمولوجيا', 'الفلك'], correctIndex: 1 },
  { id: 37, category: 'ramadan', text: 'ما هي السورة التي تسمى "سنام القران"؟', options: ['الفاتحة', 'البقرة', 'ال عمران', 'النساء'], correctIndex: 1 },
  { id: 38, category: 'ramadan', text: 'ما هي اكبر صحراء في العالم؟', options: ['الصحراء الكبرى', 'صحراء كوبي', 'القارة القطبية الجنوبية', 'الربع الخالي'], correctIndex: 2 },
  { id: 39, category: 'ramadan', text: 'كم عدد سجدات التلاوة في القران الكريم؟', options: ['10 سجدات', '12 سجدة', '15 سجدة', '11 سجدة'], correctIndex: 2 },
  { id: 40, category: 'ramadan', text: 'من هو اول من رسم خريطة للعالم؟', options: ['ابن بطوطة', 'الادريسي', 'الخوارزمي', 'البيروني'], correctIndex: 1 },

  // عالم السيارات (30 سؤال)
  { id: 251, category: 'cars', text: 'ما هي السيارة البريطانية الشهيرة التي يقودها العميل السري 007؟', options: ['أستون مارتن', 'جاغوار', 'بنتلي', 'رولز رويس'], correctIndex: 0 },
  { id: 252, category: 'cars', text: 'أي جزء في السيارة يقوم بتبريد المحرك؟', options: ['الرادياتير', 'الدينامو', 'البطارية', 'الكربيراتير'], correctIndex: 0 },

  // إسلاميات (30 سؤال)
  { id: 301, category: 'islamic', text: 'كم عدد سور القرآن الكريم؟', options: ['114', '110', '120', '112'], correctIndex: 0 },
  { id: 302, category: 'islamic', text: 'من هو أول الخلفاء الراشدين؟', options: ['أبو بكر الصديق', 'عمر بن الخطاب', 'عثمان بن عفان', 'علي بن أبي طالب'], correctIndex: 0 },
  { id: 303, category: 'islamic', text: 'ما هي أطول سورة في القرآن الكريم؟', options: ['البقرة', 'آل عمران', 'النساء', 'المائدة'], correctIndex: 0 },
  { id: 304, category: 'islamic', text: 'في أي عام كانت الهجرة النبوية؟', options: ['622 م', '610 م', '632 م', '571 م'], correctIndex: 0 },
  { id: 305, category: 'islamic', text: 'من هو النبي الذي بنى الكعبة مع ابنه؟', options: ['إبراهيم', 'موسى', 'نوح', 'عيسى'], correctIndex: 0 },
  { id: 306, category: 'islamic', text: 'كم عدد أركان الإسلام؟', options: ['5', '6', '4', '3'], correctIndex: 0 },
  { id: 307, category: 'islamic', text: 'ما هي الغزوة التي انتصر فيها المسلمون على المشركين بقلة عددهم؟', options: ['غزوة بدر', 'غزوة أحد', 'غزوة الخندق', 'غزوة حنين'], correctIndex: 0 },
  { id: 308, category: 'islamic', text: 'من هو الصحابي الملقب بذي النورين؟', options: ['عثمان بن عفان', 'علي بن أبي طالب', 'عمر بن الخطاب', 'أبو بكر الصديق'], correctIndex: 0 },
  { id: 309, category: 'islamic', text: 'ما هي السورة التي تعدل ثلث القرآن؟', options: ['الإخلاص', 'الفلق', 'الناس', 'الكافرون'], correctIndex: 0 },
  { id: 310, category: 'islamic', text: 'كم سنة استمرت الدعوة السرية في مكة؟', options: ['3 سنوات', '5 سنوات', '10 سنوات', '13 سنة'], correctIndex: 0 },
  { id: 311, category: 'islamic', text: 'من هو مؤذن الرسول صلى الله عليه وسلم؟', options: ['بلال بن رباح', 'عبدالله بن مسعود', 'أنس بن مالك', 'أبو هريرة'], correctIndex: 0 },
  { id: 312, category: 'islamic', text: 'ما هي الصلاة التي ليس لها أذان ولا إقامة؟', options: ['صلاة العيد', 'صلاة الضحى', 'صلاة الوتر', 'صلاة الجنازة'], correctIndex: 0 },
  { id: 313, category: 'islamic', text: 'من هو سيف الله المسلول؟', options: ['خالد بن الوليد', 'حمزة بن عبد المطلب', 'سعد بن أبي وقاص', 'عمار بن ياسر'], correctIndex: 0 },
  { id: 314, category: 'islamic', text: 'ما هو الكتاب المنزل على سيدنا عيسى عليه السلام؟', options: ['الإنجيل', 'التوراة', 'الزبور', 'القرآن'], correctIndex: 0 },
  { id: 315, category: 'islamic', text: 'كم عدد الرسل أولي العزم؟', options: ['5', '4', '6', '7'], correctIndex: 0 },
  { id: 316, category: 'islamic', text: 'من هي أول شهيدة في الإسلام؟', options: ['سمية بنت خياط', 'خديجة بنت خويلد', 'أسماء بنت أبي بكر', 'فاطمة الزهراء'], correctIndex: 0 },
  { id: 317, category: 'islamic', text: 'ما هي الليلة التي هي خير من ألف شهر؟', options: ['ليلة القدر', 'ليلة النصف من شعبان', 'ليلة الإسراء', 'ليلة العيد'], correctIndex: 0 },
  { id: 318, category: 'islamic', text: 'في أي مدينة يوجد المسجد الأقصى؟', options: ['القدس', 'مكة', 'المدينة', 'القاهرة'], correctIndex: 0 },
  { id: 319, category: 'islamic', text: 'من هو النبي الذي ألقي في النار ولم يحترق؟', options: ['إبراهيم', 'موسى', 'يوسف', 'يونس'], correctIndex: 0 },
  { id: 320, category: 'islamic', text: 'ما هي السورة التي تسمى "قلب القرآن"؟', options: ['يس', 'الرحمن', 'الملك', 'الواقعة'], correctIndex: 0 },
  { id: 321, category: 'islamic', text: 'كم عدد التكبيرات في الركعة الأولى من صلاة العيد؟', options: ['7', '5', '3', '4'], correctIndex: 0 },
  { id: 322, category: 'islamic', text: 'من هو الصحابي الذي اهتز لموته عرش الرحمن؟', options: ['سعد بن معاذ', 'مصعب بن عمير', 'حمزة بن عبد المطلب', 'جعفر الطيار'], correctIndex: 0 },
  { id: 323, category: 'islamic', text: 'ما هي عاصمة الدولة العباسية؟', options: ['بغداد', 'دمشق', 'القاهرة', 'المدينة'], correctIndex: 0 },
  { id: 324, category: 'islamic', text: 'من هو النبي الذي كلمه الله تكليماً؟', options: ['موسى', 'عيسى', 'إبراهيم', 'محمد'], correctIndex: 0 },
  { id: 325, category: 'islamic', text: 'ما هو الحج الأصغر؟', options: ['العمرة', 'حجة الوداع', 'يوم عرفة', 'رمي الجمرات'], correctIndex: 0 },
  { id: 326, category: 'islamic', text: 'من هو كاتب الوحي الذي جمع القرآن في عهد أبي بكر؟', options: ['زيد بن ثابت', 'علي بن أبي طالب', 'أبي بن كعب', 'عثمان بن عفان'], correctIndex: 0 },
  { id: 327, category: 'islamic', text: 'ما هي الغزوة التي جُرح فيها الرسول وكسرت رباعيته؟', options: ['غزوة أحد', 'غزوة بدر', 'غزوة الخندق', 'غزوة خيبر'], correctIndex: 0 },
  { id: 328, category: 'islamic', text: 'من هي زوجة النبي التي روت عنه أكثر الأحاديث؟', options: ['عائشة بنت أبي بكر', 'حفصة بنت عمر', 'أم سلمة', 'زينب بنت جحش'], correctIndex: 0 },
  { id: 329, category: 'islamic', text: 'كم عدد أيام التشريق؟', options: ['3', '4', '2', '5'], correctIndex: 0 },
  { id: 330, category: 'islamic', text: 'ما هو الشهر الذي أنزل فيه القرآن؟', options: ['رمضان', 'شعبان', 'محرم', 'رجب'], correctIndex: 0 },

  // كرة قدم (30 سؤال)
  { id: 351, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ كأس العالم؟', options: ['ميروسلاف كلوزه', 'رونالدو', 'بيليه', 'مارادونا'], correctIndex: 0 },
  { id: 352, category: 'football', text: 'ما هو النادي الذي فاز بدوري أبطال أوروبا أكبر عدد من المرات؟', options: ['ريال مدريد', 'برشلونة', 'بايرن ميونخ', 'ليفربول'], correctIndex: 0 },
  { id: 353, category: 'football', text: 'من هو اللاعب الذي فاز بجائزة الكرة الذهبية أكبر عدد من المرات؟', options: ['ليونيل ميسي', 'كريستيانو رونالدو', 'زين الدين زيدان', 'رونالدو نازاريو'], correctIndex: 0 },
  { id: 354, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس العالم أكبر عدد من المرات؟', options: ['البرازيل', 'ألمانيا', 'إيطاليا', 'الأرجنتين'], correctIndex: 0 },
  { id: 355, category: 'football', text: 'من هو اللاعب الذي سجل أسرع هدف في تاريخ كأس العالم؟', options: ['هاكان شوكور', 'كلوديو بيزارو', 'رونالدو', 'ميروسلاف كلوزه'], correctIndex: 0 },
  { id: 356, category: 'football', text: 'ما هو النادي الذي فاز بالدوري الإنجليزي الممتاز أكبر عدد من المرات؟', options: ['مانشستر يونايتد', 'ليفربول', 'أرسنال', 'تشيلسي'], correctIndex: 0 },
  { id: 357, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في موسم واحد في الدوري الإسباني؟', options: ['ليونيل ميسي', 'كريستيانو رونالدو', 'رونالدو نازاريو', 'راؤول'], correctIndex: 0 },
  { id: 358, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس آسيا أكبر عدد من المرات؟', options: ['اليابان', 'السعودية', 'كوريا الجنوبية', 'إيران'], correctIndex: 0 },
  { id: 359, category: 'football', text: 'من هو اللاعب الذي لعب أكبر عدد من المباريات في تاريخ كأس العالم؟', options: ['لوتار ماتيوس', 'ميroslav كلوزه', 'باولو مالديني', 'كافو'], correctIndex: 0 },
  { id: 360, category: 'football', text: 'ما هو النادي الذي فاز بدوري أبطال آسيا أكبر عدد من المرات؟', options: ['الهلال', 'الأهلي', 'بوهانغ ستيلرز', 'جونبك هيونداي'], correctIndex: 0 },
  { id: 361, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ الدوري الإنجليزي؟', options: ['آلان شيرر', 'واين روني', 'آندي كول', 'سيرجي أغويرو'], correctIndex: 0 },
  { id: 362, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس أمم أفريقيا أكبر عدد من المرات؟', options: ['مصر', 'الكاميرون', 'غانا', 'نيجيريا'], correctIndex: 0 },
  { id: 363, category: 'football', text: 'من هو اللاعب الذي فاز بكأس العالم كلاعب ومدرب؟', options: ['فرانز بيكنباور', 'ديدييه ديشان', 'ماريو زاغالو', 'أريغو ساكي'], correctIndex: 2 },
  { id: 364, category: 'football', text: 'ما هو النادي الذي فاز بالدوري الإيطالي أكبر عدد من المرات؟', options: ['يوفنتوس', 'ميلان', 'إنتر ميلان', 'روما'], correctIndex: 0 },
  { id: 365, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ دوري أبطال أوروبا؟', options: ['كريستيانو رونالدو', 'ليونيل ميسي', 'راؤول', 'روبرت ليفاندوفسكي'], correctIndex: 0 },
  { id: 366, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس القارات أكبر عدد من المرات؟', options: ['البرازيل', 'الأرجنتين', 'فرنسا', 'ألمانيا'], correctIndex: 0 },
  { id: 367, category: 'football', text: 'من هو اللاعب الذي لعب أكبر عدد من المباريات في تاريخ الدوري الإسباني؟', options: ['أندوني زوبيزاريتا', 'راؤول', 'كارليس بويول', 'سيرخيو راموس'], correctIndex: 0 },
  { id: 368, category: 'football', text: 'ما هو النادي الذي فاز بالدوري الألماني أكبر عدد من المرات؟', options: ['بايرن ميونخ', 'بوروسيا دورتموند', 'هامبورغ', 'شتوتغارت'], correctIndex: 0 },
  { id: 369, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ المنتخب البرازيلي؟', options: ['بيليه', 'رونالدو', 'نيمار', 'زيكو'], correctIndex: 1 },
  { id: 370, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس العالم للسيدات أكبر عدد من المرات؟', options: ['الولايات المتحدة', 'ألمانيا', 'النرويج', 'اليابان'], correctIndex: 0 },
  { id: 371, category: 'football', text: 'من هو اللاعب الذي فاز بجائزة أفضل لاعب في العالم من الفيفا أكبر عدد من المرات؟', options: ['ليونيل ميسي', 'كريستيانو رونالدو', 'زين الدين زيدان', 'رونالدو نازاريو'], correctIndex: 0 },
  { id: 372, category: 'football', text: 'ما هو النادي الذي فاز بدوري أبطال أفريقيا أكبر عدد من المرات؟', options: ['الأهلي', 'الزمالك', 'تي بي مازيمبي', 'الترجي'], correctIndex: 0 },
  { id: 373, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ الدوري الإيطالي؟', options: ['سيلفيو بيولا', 'فرانشيسكو توتي', 'روبرتو باجو', 'ألساندرو دل بييرو'], correctIndex: 0 },
  { id: 374, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس العالم تحت 20 سنة أكبر عدد من المرات؟', options: ['الأرجنتين', 'البرازيل', 'إسبانيا', 'ألمانيا'], correctIndex: 0 },
  { id: 375, category: 'football', text: 'من هو اللاعب الذي لعب أكبر عدد من المباريات في تاريخ الدوري الإنجليزي؟', options: ['غاري سبيد', 'ريان جيجز', 'فرانك لامبارد', 'ستيفن جيرارد'], correctIndex: 1 },
  { id: 376, category: 'football', text: 'ما هو النادي الذي فاز بالدوري الفرنسي أكبر عدد من المرات؟', options: ['سانت إتيان', 'باريس سان جيرمان', 'مارسيليا', 'ليون'], correctIndex: 0 },
  { id: 377, category: 'football', text: 'من هو اللاعب الذي سجل أكبر عدد من الأهداف في تاريخ المنتخب الأرجنتيني؟', options: ['ليونيل ميسي', 'غابرييل باتيستوتا', 'دييجو مارادونا', 'سيرخيو أغويرو'], correctIndex: 0 },
  { id: 378, category: 'football', text: 'ما هو المنتخب الذي فاز بكأس العالم تحت 17 سنة أكبر عدد من المرات؟', options: ['البرازيل', 'نيجيريا', 'المكسيك', 'إسبانيا'], correctIndex: 1 },
  { id: 379, category: 'football', text: 'من هو اللاعب الذي فاز بجائزة الحذاء الذهبي الأوروبي أكبر عدد من المرات؟', options: ['ليونيل ميسي', 'كريستيانو رونالدو', 'توماس مولر', 'لويس سواريز'], correctIndex: 0 },
  { id: 380, category: 'football', text: 'ما هو النادي الذي فاز بكأس السوبر الأوروبي أكبر عدد من المرات؟', options: ['ميلان', 'ريال مدريد', 'برشلونة', 'بايرن ميونخ'], correctIndex: 0 },

  // عالم الحيوان (30 سؤال)
  { id: 401, category: 'animals', text: 'ما هو أسرع حيوان بري في العالم؟', options: ['الفهد', 'الأسد', 'النمر', 'الذئب'], correctIndex: 0 },
  { id: 402, category: 'animals', text: 'ما هو أكبر حيوان في العالم؟', options: ['الحوت الأزرق', 'الفيل', 'الديناصور', 'الحوت القاتل'], correctIndex: 0 },
  { id: 403, category: 'animals', text: 'ما هو الحيوان الذي يسمى "ملك الغابة"؟', options: ['الأسد', 'النمر', 'الفهد', 'الذئب'], correctIndex: 0 },
  { id: 404, category: 'animals', text: 'ما هو الحيوان الذي ينام وعيناه مفتوحتان؟', options: ['الدولفين', 'السمكة', 'التمساح', 'الحوت'], correctIndex: 0 },
  { id: 405, category: 'animals', text: 'ما هو الحيوان الذي يمتلك أقوى عضة في العالم؟', options: ['التمساح', 'الأسد', 'النمر', 'الذئب'], correctIndex: 0 },
  { id: 406, category: 'animals', text: 'ما هو الحيوان الذي يسمى "سفينة الصحراء"؟', options: ['الجمل', 'الحصان', 'الحمار', 'البعير'], correctIndex: 0 },
  { id: 407, category: 'animals', text: 'ما هو الحيوان الذي يملك أطول عمر؟', options: ['السلحفاة', 'الفيل', 'الحوت', 'النسر'], correctIndex: 0 },
  { id: 408, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الطائر الجمل"؟', options: ['النعامة', 'النسر', 'الصقر', 'البطريق'], correctIndex: 0 },
  { id: 409, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر دماغ نسبة إلى حجم جسمه؟', options: ['الدولفين', 'الفيل', 'الحوت', 'الشمبانزي'], correctIndex: 0 },
  { id: 410, category: 'animals', text: 'ما هو الحيوان الذي يملك حاسة شم قوية جداً؟', options: ['الكلب', 'الأسد', 'النمر', 'الذئب'], correctIndex: 0 },
  { id: 411, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان الكسول"؟', options: ['الكسلان', 'الدب', 'الفهد', 'النمر'], correctIndex: 0 },
  { id: 412, category: 'animals', text: 'ما هو الحيوان الذي يملك أعلى صوت في العالم؟', options: ['الحوت الأزرق', 'الفيل', 'الأسد', 'النمر'], correctIndex: 0 },
  { id: 413, category: 'animals', text: 'ما هو الحيوان الذي يملك أسرع قلب في العالم؟', options: ['الطائر الطنان', 'الفأر', 'الخفاش', 'العصفور'], correctIndex: 0 },
  { id: 414, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر عيون في العالم؟', options: ['الحبار العملاق', 'الفيل', 'الحوت', 'الدب'], correctIndex: 0 },
  { id: 415, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان النظيف"؟', options: ['القط', 'الكلب', 'الأرنب', 'الفأر'], correctIndex: 0 },
  { id: 416, category: 'animals', text: 'ما هو الحيوان الذي يملك أقوى حاسة سمع؟', options: ['الخفاش', 'الفيل', 'الكلب', 'الذئب'], correctIndex: 0 },
  { id: 417, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان المدرع"؟', options: ['المدرع', 'السلحفاة', 'القنفذ', 'التمساح'], correctIndex: 0 },
  { id: 418, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر قدم في العالم؟', options: ['الفيل', 'الدب', 'الزرافة', 'الحوت'], correctIndex: 0 },
  { id: 419, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان المائي"؟', options: ['السمكة', 'الدولفين', 'الحوت', 'التمساح'], correctIndex: 0 },
  { id: 420, category: 'animals', text: 'ما هو الحيوان الذي يملك أسرع حركة في العالم؟', options: ['الصقر', 'الفهد', 'الأسد', 'النمر'], correctIndex: 0 },
  { id: 421, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان الليلي"؟', options: ['البومة', 'الخفاش', 'الثعلب', 'الذئب'], correctIndex: 0 },
  { id: 422, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر قرون في العالم؟', options: ['الموظ', 'الغزال', 'الثور', 'الكبش'], correctIndex: 0 },
  { id: 423, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان الاجتماعي"؟', options: ['النحل', 'النمل', 'الذئب', 'الدولفين'], correctIndex: 0 },
  { id: 424, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر جناحين في العالم؟', options: ['النسر', 'الطائر الجارح', 'البطريق', 'الخفاش'], correctIndex: 0 },
  { id: 425, category: 'animals', text: 'ما هو الحيوان الذي يسمى "الحيوان الصامت"؟', options: ['السمكة', 'السلحفاة', 'الأفعى', 'العقرب'], correctIndex: 0 },
  { id: 426, category: 'animals', text: 'ما هو الحيوان الذي يملك أكبر عدد من الأسنان؟', options: ['الحلزون', 'القرش', 'التمساح', 'الفيل'], correctIndex: 1 },

  // ألعاب فيديو (30 سؤال)
  { id: 451, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة البقاء"؟', options: ['ماينكرافت', 'فورتنايت', 'ببجي', 'روبلكس'], correctIndex: 0 },
  { id: 452, category: 'gaming', text: 'من هو بطل لعبة "سوبر ماريو"؟', options: ['ماريو', 'لويجي', 'باولين', 'يوشي'], correctIndex: 0 },
  { id: 453, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة السيارات"؟', options: ['فورزا هورايزون', 'جراند ثيفت أوتو', 'نيد فور سبيد', 'فيفا'], correctIndex: 0 },
  { id: 454, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "ذا ليجند أوف زيلدا"؟', options: ['غانون', 'زيلدا', 'لينك', 'دارك نوت'], correctIndex: 0 },
  { id: 455, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة القتال"؟', options: ['ستريت فايتر', 'مورتال كومبات', 'تيكين', 'سول كاليبور'], correctIndex: 0 },
  { id: 456, category: 'gaming', text: 'من هو البطل في لعبة "هالو"؟', options: ['ماستر شيف', 'كورتانا', 'ذا أربيتر', 'جون'], correctIndex: 0 },
  { id: 457, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الرعب"؟', options: ['ريسيدنت إيفل', 'سايلنت هيل', 'أوت لاست', 'فايف نايتس آت فريديز'], correctIndex: 0 },
  { id: 458, category: 'gaming', text: 'من هو البطل في لعبة "أونشارتد"؟', options: ['ناثان دريك', 'إيلينا فيشر', 'فيكتور سوليفان', 'تشلوي فرايزر'], correctIndex: 0 },
  { id: 459, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة المغامرة"؟', options: ['ذا ليجند أوف زيلدا', 'أونشارتد', 'تومب رايدر', 'أساسنز كريد'], correctIndex: 0 },
  { id: 460, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "فاينل فانتازي"؟', options: ['سيفيروس', 'كلاود', 'تيفا', 'سيبيروث'], correctIndex: 3 },
  { id: 461, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة المحاكاة"؟', options: ['ذا سيمز', 'ماينكرافت', 'ستارديو فالي', 'أنيمل كروسينغ'], correctIndex: 0 },
  { id: 462, category: 'gaming', text: 'من هو البطل في لعبة "ميتال جير سوليد"؟', options: ['سوليد سنيك', 'ليكيد سنيك', 'بيج بوس', 'أوتيكون'], correctIndex: 0 },
  { id: 463, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة السباق"؟', options: ['فورزا هورايزون', 'جران توريزمو', 'نيد فور سبيد', 'فيفا'], correctIndex: 0 },
  { id: 464, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "بايونيتا"؟', options: ['بايونيتا', 'جين', 'بالدر', 'لوكا'], correctIndex: 2 },
  { id: 465, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الأكشن"؟', options: ['كال أوف ديوتي', 'باتلفيلد', 'هالو', 'جيرز أوف وور'], correctIndex: 0 },
  { id: 466, category: 'gaming', text: 'من هو البطل في لعبة "ديوس إكس"؟', options: ['آدم جنسن', 'JC دنتون', 'بول دنتون', 'الياس ديفو'], correctIndex: 0 },
  { id: 467, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الألغاز"؟', options: ['بورتال', 'ذا تالوس برينسبل', 'ذا فيغورو أوت', 'أنتي تشامبر'], correctIndex: 0 },
  { id: 468, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "ذا لاست أوف أس"؟', options: ['ديفيد', 'مارلين', 'جويل', 'إيلي'], correctIndex: 0 },
  { id: 469, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الاستراتيجية"؟', options: ['ستاركرافت', 'أيج أوف إمبايرز', 'سيفيليزيشن', 'توتال وار'], correctIndex: 0 },
  { id: 470, category: 'gaming', text: 'من هو البطل في لعبة "هيت مان"؟', options: ['أجنت 47', 'ديانا', 'لوكاس غراي', 'أرثر إدواردز'], correctIndex: 0 },
  { id: 471, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الرياضة"؟', options: ['فيفا', 'نيد فور سبيد', 'فورزا هورايزون', 'جران توريزمو'], correctIndex: 0 },
  { id: 472, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "باتمان: آركام أسايلم"؟', options: ['الجوكر', 'هارلي كوين', 'بين', 'راس آل غول'], correctIndex: 0 },
  { id: 473, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة المغامرة النصية"؟', options: ['ذا ووكينغ ديد', 'لايف إز سترينج', 'ذا وولف أمونغ أس', 'أنتي رودروم'], correctIndex: 0 },
  { id: 474, category: 'gaming', text: 'من هو البطل في لعبة "أساسنز كريد"؟', options: ['إيزيو أوديتوري', 'ألتير إبن لا عهد', 'باييك', 'كونور'], correctIndex: 0 },
  { id: 475, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة البقاء على قيد الحياة"؟', options: ['ذا فورست', 'ساب نوتيكا', 'غراوندد', 'داي زي'], correctIndex: 0 },
  { id: 476, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "ماس إفكت"؟', options: ['سارين', 'ذا ريبيرز', 'ذا كولكتور', 'ذا ثوري'], correctIndex: 0 },
  { id: 477, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة المحاكاة الاقتصادية"؟', options: ['سينت مايكل', 'أوبن تي تي دي', 'تروبيكو', 'سينت أندرياس'], correctIndex: 0 },
  { id: 478, category: 'gaming', text: 'من هو البطل في لعبة "فال أوت"؟', options: ['ذا فولت ديلر', 'ذا لونلي وندر', 'ذا كوريير', 'ذا سولي سرفايفر'], correctIndex: 2 },
  { id: 479, category: 'gaming', text: 'ما هي اللعبة التي تسمى "لعبة الأكشن والمغامرة"؟', options: ['أونشارتد', 'تومب رايدر', 'ذا ليجند أوف زيلدا', 'أساسنز كريد'], correctIndex: 0 },
  { id: 480, category: 'gaming', text: 'من هو الشرير الرئيسي في لعبة "ذا ويتشر"؟', options: ['إمير', 'رادوفيد', 'غونتير', 'سيريل'], correctIndex: 1 },

  // أنمي ومانجا (30 سؤال)
  { id: 501, category: 'anime', text: 'ما هو الأنمي الذي تدور أحداثه حول "أكاديمية الأبطال"؟', options: ['ماي هيرو أكاديميا', 'ناروتو', 'ون بيس', 'أيتاكي نو كيوشي'], correctIndex: 0 },
  { id: 502, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "ناروتو"؟', options: ['ناروتو أوزوماتشي', 'ساسكي أوتشيها', 'ساكورا هارونو', 'كاكاشي هاتاكي'], correctIndex: 0 },
  { id: 503, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "الصيادين"؟', options: ['هنتر x هنتر', 'ون بيس', 'بليتش', 'دراغون بول'], correctIndex: 0 },
  { id: 504, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "أيتاكي نو كيوشي"؟', options: ['سايتاما', 'جينوس', 'غارو', 'بوروس'], correctIndex: 2 },
  { id: 505, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "لعبة كرة القدم"؟', options: ['إنازوما إليفن', 'كابتن تسوباسا', 'هايكيو!!', 'كوروكو نو باسكت'], correctIndex: 0 },
  { id: 506, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "دراغون بول"؟', options: ['سون غوكو', 'فيجيتا', 'بيكولو', 'كريلين'], correctIndex: 0 },
  { id: 507, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "القراصنة"؟', options: ['ون بيس', 'ناروتو', 'بليتش', 'هنتر x هنتر'], correctIndex: 0 },
  { id: 508, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "بليتش"؟', options: ['سوسكي آيزن', 'إيشين كوروساكي', 'روكيا كوتشيكي', 'أوريهيمي إينوي'], correctIndex: 0 },
  { id: 509, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "كرة السلة"؟', options: ['كوروكو نو باسكت', 'هايكيو!!', 'كابتن تسوباسا', 'إنازوما إليفن'], correctIndex: 0 },
  { id: 510, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "أيتاكي نو كيوشي"？', options: ['سايتاما', 'جينوس', 'غارو', 'بوروس'], correctIndex: 0 },
  { id: 511, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "الطموح"؟', options: ['هايكيو!!', 'كوروكو نو باسكت', 'كابتن تسوباسا', 'إنازوما إليفن'], correctIndex: 0 },
  { id: 512, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "دراغون بول"؟', options: ['فريزا', 'سيل', 'بوي', 'ماجين بوي'], correctIndex: 0 },
  { id: 513, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "الشطرنج"؟', options: ['ماتسوري', 'شوغي', 'غو', 'شوجي'], correctIndex: 1 },
  { id: 514, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "هنتر x هنتر"？', options: ['غون فريكس', 'كيلوا زولديك', 'ليوريو', 'كورابيكا'], correctIndex: 0 },
  { id: 515, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "السباقات"؟', options: ['إنيشل دي', 'سبيد راسر', 'ريدلاين', 'كابتن تسوباسا'], correctIndex: 0 },
  { id: 516, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "ناروتو"؟', options: ['أوروتشيمارو', 'كابوتو', 'أوبيتو', 'مادارا'], correctIndex: 0 },
  { id: 517, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "الموسيقى"؟', options: ['يوريكامي', 'بيك', 'نودام كانتابيلي', 'ك-أون!'], correctIndex: 0 },
  { id: 518, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "بليتش"？', options: ['إيتشيغو كوروساكي', 'رينجي أباي', 'أوريهيمي إينوي', 'روسيا كوتشيكي'], correctIndex: 0 },
  { id: 519, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "الطبخ"؟', options: ['شوكوغكي نو سوما', 'يوريكامي', 'بيك', 'نودام كانتابيلي'], correctIndex: 0 },
  { id: 520, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "هنتر x هنتر"？', options: ['ميريام', 'شيزوكو', 'كايتو', 'هيسوكا'], correctIndex: 3 },
  { id: 521, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "الرسم"؟', options: ['باكومان', 'شوكوغكي نو سوما', 'يوريكامي', 'بيك'], correctIndex: 0 },
  { id: 522, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "كوروكو نو باسكت"？', options: ['كوروكو تيغا', 'تايكا كايسي', 'شينتارو ميدوروما', 'دايكي أومين'], correctIndex: 0 },
  { id: 523, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "الكتابة"؟', options: ['باكومان', 'شوكوغكي نو سوما', 'يوريكامي', 'بيك'], correctIndex: 0 },
  { id: 524, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "دراغون بول"؟', options: ['سيل', 'بوي', 'فريزا', 'ماجين بوي'], correctIndex: 2 },
  { id: 525, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "الرقص"؟', options: ['يوريكامي', 'بيك', 'نودام كانتابيلي', 'ك-أون!'], correctIndex: 0 },
  { id: 526, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "هايكيو!!"？', options: ['شويهي هيناتا', 'توبيو كاغياما', 'كيشين أويكاوا', 'دايسي سوغاوارا'], correctIndex: 0 },
  { id: 527, category: 'anime', text: 'ما هو الأنمي الذي يتحدث عن "التمثيل"؟', options: ['أكتريس', 'يوريكامي', 'بيك', 'نودام كانتابيلي'], correctIndex: 0 },
  { id: 528, category: 'anime', text: 'من هو الشرير الرئيسي في أنمي "بليتش"؟', options: ['أولكورا', 'غرانز', 'باراغان', 'أيزن'], correctIndex: 3 },
  { id: 529, category: 'anime', text: 'ما هو الأنمي الذي يدور حول "التصوير"؟', options: ['باكومان', 'شوكوغكي نو سوما', 'يوريكامي', 'بيك'], correctIndex: 0 },
  { id: 530, category: 'anime', text: 'من هو البطل الرئيسي في أنمي "ناروتو"؟', options: ['ساسكي', 'ناروتو', 'ساكورا', 'كاكاشي'], correctIndex: 1 },

  // تاريخ (30 سؤال)
  { id: 551, category: 'history', text: 'من هو أول رئيس للولايات المتحدة الأمريكية؟', options: ['جورج واشنطن', 'توماس جيفرسون', 'أبراهام لنكولن', 'جون آدمز'], correctIndex: 0 },
  { id: 552, category: 'history', text: 'متى بدأت الحرب العالمية الأولى؟', options: ['1914', '1918', '1939', '1945'], correctIndex: 0 },
  { id: 553, category: 'history', text: 'من هو القائد الذي فتح القسطنطينية؟', options: ['محمد الفاتح', 'صلاح الدين الأيوبي', 'عمر بن الخطاب', 'سليمان القانوني'], correctIndex: 0 },
  { id: 554, category: 'history', text: 'ما هي الحضارة التي بنت الأهرامات؟', options: ['الحضارة الفرعونية', 'الحضارة البابلية', 'الحضارة الرومانية', 'الحضارة اليونانية'], correctIndex: 0 },
  { id: 555, category: 'history', text: 'من هو مؤسس الدولة الأموية؟', options: ['معاوية بن أبي سفيان', 'عبد الملك بن مروان', 'عمر بن عبد العزيز', 'يزيد بن معاوية'], correctIndex: 0 },
  { id: 556, category: 'history', text: 'متى سقطت الدولة العثمانية؟', options: ['1924', '1918', '1923', '1920'], correctIndex: 0 },
  { id: 557, category: 'history', text: 'من هو القائد الذي هزم الصليبيين في معركة حطين؟', options: ['صلاح الدين الأيوبي', 'نور الدين زنكي', 'عماد الدين زنكي', 'الظاهر بيبرس'], correctIndex: 0 },
  { id: 558, category: 'history', text: 'ما هي المعركة التي أوقفت الزحف المغولي على العالم الإسلامي؟', options: ['عين جالوت', 'حطين', 'القادسية', 'اليرموك'], correctIndex: 0 },
  { id: 559, category: 'history', text: 'من هو مؤسس الدولة العباسية؟', options: ['أبو العباس السفاح', 'أبو جعفر المنصور', 'هارون الرشيد', 'المأمون'], correctIndex: 0 },
  { id: 560, category: 'history', text: 'متى وقعت الحرب العالمية الثانية؟', options: ['1939-1945', '1914-1918', '1950-1953', '1960-1975'], correctIndex: 0 },
  { id: 561, category: 'history', text: 'من هو القائد الذي بنى سور الصين العظيم؟', options: ['تشين شي هوانج', 'كونفوشيوس', 'ماو تسي تونغ', 'صن تزو'], correctIndex: 0 },
  { id: 562, category: 'history', text: 'ما هي المدينة التي كانت عاصمة الدولة الأموية؟', options: ['دمشق', 'بغداد', 'القاهرة', 'المدينة المنورة'], correctIndex: 0 },
  { id: 563, category: 'history', text: 'من هو العالم الذي اكتشف الجاذبية؟', options: ['إسحاق نيوتن', 'أينشتاين', 'غاليليو', 'كوبرنيكوس'], correctIndex: 0 },
  { id: 564, category: 'history', text: 'متى تم بناء برج إيفل؟', options: ['1889', '1900', '1850', '1920'], correctIndex: 0 },
  { id: 565, category: 'history', text: 'من هو القائد الذي فتح مصر؟', options: ['عمرو بن العاص', 'خالد بن الوليد', 'سعد بن أبي وقاص', 'أبو عبيدة بن الجراح'], correctIndex: 0 },
  { id: 566, category: 'history', text: 'ما هي الدولة التي كانت تسمى بلاد الفرس؟', options: ['إيران', 'العراق', 'تركيا', 'سوريا'], correctIndex: 0 },
  { id: 567, category: 'history', text: 'من هو مؤسس الدولة الأيوبية؟', options: ['صلاح الدين الأيوبي', 'نور الدين زنكي', 'شيركوه', 'نجم الدين أيوب'], correctIndex: 0 },
  { id: 568, category: 'history', text: 'متى استقلت الجزائر عن فرنسا؟', options: ['1962', '1954', '1960', '1958'], correctIndex: 0 },
  { id: 569, category: 'history', text: 'من هو القائد الذي قاد المسلمين في معركة القادسية؟', options: ['سعد بن أبي وقاص', 'خالد بن الوليد', 'المثنى بن حارثة', 'النعمان بن مقرن'], correctIndex: 0 },
  { id: 570, category: 'history', text: 'ما هي الحضارة التي اخترعت الكتابة المسمارية؟', options: ['السومرية', 'المصرية', 'البابلية', 'الآشورية'], correctIndex: 0 },
  { id: 571, category: 'history', text: 'من هو أول رائد فضاء في العالم؟', options: ['يوري جاجارين', 'نيل أرمسترونج', 'باز ألدرين', 'مايكل كولينز'], correctIndex: 0 },
  { id: 572, category: 'history', text: 'متى سقط جدار برلين؟', options: ['1989', '1990', '1961', '1991'], correctIndex: 0 },
  { id: 573, category: 'history', text: 'من هو القائد الذي أسس المملكة المتحدة؟', options: ['وليام الفاتح', 'هنري الثامن', 'إليزابيث الأولى', 'فيكتوريا'], correctIndex: 0 },
  { id: 574, category: 'history', text: 'ما هي المعركة التي انتصر فيها المسلمون على الروم في الشام؟', options: ['اليرموك', 'القادسية', 'مؤتة', 'أجنادين'], correctIndex: 0 },
  { id: 575, category: 'history', text: 'من هو العالم الذي اخترع المصباح الكهربائي؟', options: ['توماس إديسون', 'نيكولا تيسلا', 'ألكسندر بيل', 'ماركوني'], correctIndex: 0 },
  { id: 576, category: 'history', text: 'متى تم اكتشاف البنسلين؟', options: ['1928', '1930', '1940', '1920'], correctIndex: 0 },

  // علوم (30 سؤال)
  { id: 601, category: 'science', text: 'ما هو العنصر الكيميائي الذي رمزه O؟', options: ['الأكسجين', 'الذهب', 'الكربون', 'الحديد'], correctIndex: 0 },
  { id: 602, category: 'science', text: 'ما هو أكبر كوكب في المجموعة الشمسية؟', options: ['المشتري', 'زحل', 'الأرض', 'المريخ'], correctIndex: 0 },
  { id: 603, category: 'science', text: 'ما هي الوحدة التي تستخدم لقياس القوة؟', options: ['نيوتن', 'جول', 'واط', 'فولت'], correctIndex: 0 },
  { id: 604, category: 'science', text: 'ما هو العضو الذي يضخ الدم في جسم الإنسان؟', options: ['القلب', 'الرئة', 'الكبد', 'الكلى'], correctIndex: 0 },
  { id: 605, category: 'science', text: 'ما هو الغاز الذي نستخدمه للتنفس؟', options: ['الأكسجين', 'ثاني أكسيد الكربون', 'النيتروجين', 'الهيدروجين'], correctIndex: 0 },
  { id: 606, category: 'science', text: 'كم عدد ألوان قوس قزح؟', options: ['7', '6', '5', '8'], correctIndex: 0 },
  { id: 607, category: 'science', text: 'ما هو أصغر كوكب في المجموعة الشمسية؟', options: ['عطارد', 'الزهرة', 'المريخ', 'بلوتو'], correctIndex: 0 },
  { id: 608, category: 'science', text: 'ما هي سرعة الضوء؟', options: ['300', '000 كم/ث', '150', '000 كم/ث', '100', '000 كم/ث', '500', '000 كم/ث'], correctIndex: 0 },
  { id: 609, category: 'science', text: 'ما هو الجزء المسؤول عن التفكير في الدماغ؟', options: ['المخ', 'المخيخ', 'جذع الدماغ', 'النخاع الشوكي'], correctIndex: 0 },
  { id: 610, category: 'science', text: 'ما هو العنصر الذي تتكون منه الماس؟', options: ['الكربون', 'الحديد', 'الذهب', 'الفضة'], correctIndex: 0 },
  { id: 611, category: 'science', text: 'ما هو الحيوان الذي يعتبر من الثدييات ولكنه يبيض؟', options: ['خلد الماء', 'الخفاش', 'الدولفين', 'الحوت'], correctIndex: 0 },
  { id: 612, category: 'science', text: 'ما هو أثقل معدن في العالم؟', options: ['الأوزميوم', 'الذهب', 'الرصاص', 'الزئبق'], correctIndex: 0 },
  { id: 613, category: 'science', text: 'ما هو الكوكب الأحمر؟', options: ['المريخ', 'المشتري', 'زحل', 'الزهرة'], correctIndex: 0 },
  { id: 614, category: 'science', text: 'ما هو الغاز الذي يسبب الاحتباس الحراري؟', options: ['ثاني أكسيد الكربون', 'الأكسجين', 'النيتروجين', 'الهيدروجين'], correctIndex: 0 },
  { id: 615, category: 'science', text: 'ما هي أصغر وحدة في الكائن الحي؟', options: ['الخلية', 'الذرة', 'الجزيء', 'النسيج'], correctIndex: 0 },
  { id: 616, category: 'science', text: 'ما هو العنصر الذي يستخدم في صناعة البطاريات؟', options: ['الليثيوم', 'الحديد', 'النحاس', 'الألمنيوم'], correctIndex: 0 },
  { id: 617, category: 'science', text: 'ما هو الفيتامين الذي نحصل عليه من الشمس؟', options: ['فيتامين د', 'فيتامين سي', 'فيتامين أ', 'فيتامين ب'], correctIndex: 0 },
  { id: 618, category: 'science', text: 'ما هو المعدن السائل في درجة حرارة الغرفة؟', options: ['الزئبق', 'الحديد', 'النحاس', 'الألمنيوم'], correctIndex: 0 },
  { id: 619, category: 'science', text: 'ما هو الكوكب الذي لديه حلقات؟', options: ['زحل', 'المشتري', 'أورانوس', 'نبتون'], correctIndex: 0 },
  { id: 620, category: 'science', text: 'ما هو الغاز الذي يستخدم في البالونات؟', options: ['الهيليوم', 'الأكسجين', 'النيتروجين', 'الهيدروجين'], correctIndex: 0 },
  { id: 621, category: 'science', text: 'ما هو العضو الذي يصفي الدم في الجسم؟', options: ['الكلية', 'الكبد', 'القلب', 'الرئة'], correctIndex: 0 },
  { id: 622, category: 'science', text: 'ما هو العنصر الذي يتكون منه الماء؟', options: ['الهيدروجين والأكسجين', 'الكربون والأكسجين', 'النيتروجين والأكسجين', 'الهيدروجين والنيتروجين'], correctIndex: 0 },
  { id: 623, category: 'science', text: 'ما هو الكوكب الذي يسمى "نجمة الصباح"؟', options: ['الزهرة', 'المريخ', 'عطارد', 'زحل'], correctIndex: 0 },
  { id: 624, category: 'science', text: 'ما هو الجزء المسؤول عن التنفس في النبات؟', options: ['الأوراق', 'الجذور', 'الساق', 'الزهور'], correctIndex: 0 },
  { id: 625, category: 'science', text: 'ما هو الحيوان الذي يستطيع تغيير لونه؟', options: ['الحرباء', 'الأخطبوط', 'السمكة', 'الضفدع'], correctIndex: 0 },
  { id: 626, category: 'science', text: 'ما هو المعدن الذي يوصل الكهرباء بشكل أفضل؟', options: ['الفضة', 'النحاس', 'الذهب', 'الألمنيوم'], correctIndex: 0 },
  { id: 627, category: 'science', text: 'ما هو الكوكب الأقرب إلى الأرض؟', options: ['الزهرة', 'المريخ', 'عطارد', 'المشتري'], correctIndex: 0 },
  { id: 628, category: 'science', text: 'ما هو الغاز الأكثر وفرة في الغلاف الجوي؟', options: ['النيتروجين', 'الأكسجين', 'ثاني أكسيد الكربون', 'الأرجون'], correctIndex: 0 },
  { id: 629, category: 'science', text: 'ما هو العضو الذي يتحكم في التوازن؟', options: ['الأذن الداخلية', 'المخ', 'العيون', 'الأنف'], correctIndex: 0 },
  { id: 630, category: 'science', text: 'ما هو العنصر الذي يستخدم في صناعة الزجاج؟', options: ['السيليكون', 'الحديد', 'النحاس', 'الألمنيوم'], correctIndex: 0 },

  // ثقافة سعودية (30 سؤال)
  { id: 651, category: 'saudi', text: 'ما هي عاصمة المملكة العربية السعودية؟', options: ['الرياض', 'جدة', 'الدمام', 'مكة'], correctIndex: 0 },
  { id: 652, category: 'saudi', text: 'ما هو العملة المستخدمة في السعودية؟', options: ['الريال', 'الدينار', 'الدرهم', 'الجنيه'], correctIndex: 0 },
  { id: 653, category: 'saudi', text: 'متى تأسست المملكة العربية السعودية؟', options: ['1932', '1902', '1925', '1930'], correctIndex: 0 },
  { id: 654, category: 'saudi', text: 'ما هي أكبر مدينة في السعودية من حيث المساحة؟', options: ['الدمام', 'الرياض', 'جدة', 'الطائف'], correctIndex: 1 },
  { id: 655, category: 'saudi', text: 'ما هو الميناء الرئيسي للمملكة على البحر الأحمر؟', options: ['جدة', 'ينبع', 'الدمام', 'جازان'], correctIndex: 0 },
  { id: 656, category: 'saudi', text: 'ما هو الجبل الأعلى في السعودية؟', options: ['جبل السودة', 'جبل اللوز', 'جبل فيفا', 'جبل شمر'], correctIndex: 0 },
  { id: 657, category: 'saudi', text: 'ما هي المنطقة التي تشتهر بزراعة النخيل؟', options: ['القصيم', 'عسير', 'الجوف', 'تبوك'], correctIndex: 0 },
  { id: 658, category: 'saudi', text: 'ما هو الشعار الوطني للمملكة؟', options: ['سيفان ونخلة', 'نسر', 'صقر', 'أسد'], correctIndex: 0 },
  { id: 659, category: 'saudi', text: 'من هو مؤسس المملكة العربية السعودية الثالثة؟', options: ['الملك عبدالعزيز', 'الملك سعود', 'الملك فيصل', 'الملك خالد'], correctIndex: 0 },
  { id: 660, category: 'saudi', text: 'ما هي المدينة التي تقع فيها الكعبة المشرفة؟', options: ['مكة المكرمة', 'المدينة المنورة', 'الرياض', 'جدة'], correctIndex: 0 },
  { id: 661, category: 'saudi', text: 'ما هو الاسم القديم للرياض؟', options: ['حجر اليمامة', 'يثرب', 'فدك', 'تيماء'], correctIndex: 0 },
  { id: 662, category: 'saudi', text: 'ما هي المنطقة التي تشتهر بالورد؟', options: ['الطائف', 'أبها', 'الباحة', 'جازان'], correctIndex: 0 },
  { id: 663, category: 'saudi', text: 'ما هو المطار الدولي الرئيسي في الرياض؟', options: ['مطار الملك خالد', 'مطار الملك عبدالعزيز', 'مطار الملك فهد', 'مطار الأمير محمد بن عبدالعزيز'], correctIndex: 0 },
  { id: 664, category: 'saudi', text: 'ما هي الأكلة الشعبية الأشهر في السعودية؟', options: ['الكبسة', 'المندي', 'الجريش', 'المرقوق'], correctIndex: 0 },
  { id: 665, category: 'saudi', text: 'ما هو البحر الذي يحد السعودية من الغرب؟', options: ['البحر الأحمر', 'الخليج العربي', 'بحر العرب', 'المحيط الهندي'], correctIndex: 0 },
  { id: 666, category: 'saudi', text: 'ما هي المدينة التي تسمى عروس البحر الأحمر؟', options: ['جدة', 'الدمام', 'ينبع', 'الخبر'], correctIndex: 0 },
  { id: 667, category: 'saudi', text: 'ما هو الحيوان الوطني للسعودية؟', options: ['الجمل', 'المها العربي', 'الصقر', 'الحصان العربي'], correctIndex: 0 },
  { id: 668, category: 'saudi', text: 'ما هي المنطقة التي تشتهر بالزيتون؟', options: ['الجوف', 'تبوك', 'حائل', 'القصيم'], correctIndex: 0 },
  { id: 669, category: 'saudi', text: 'ما هو الوادي الأشهر في الرياض؟', options: ['وادي حنيفة', 'وادي الرمة', 'وادي الدواسر', 'وادي فاطمة'], correctIndex: 0 },
  { id: 670, category: 'saudi', text: 'ما هي المدينة الصناعية الكبرى في شرق المملكة؟', options: ['الجبيل', 'الخبر', 'الدمام', 'الظهران'], correctIndex: 0 },
  { id: 671, category: 'saudi', text: 'ما هو اللقب الذي يطلق على ملوك السعودية؟', options: ['خادم الحرمين الشريفين', 'أمير المؤمنين', 'السلطان', 'الشاه'], correctIndex: 0 },
  { id: 672, category: 'saudi', text: 'ما هي المنطقة التي تقع فيها مدائن صالح؟', options: ['المدينة المنورة', 'تبوك', 'حائل', 'الجوف'], correctIndex: 0 },
  { id: 673, category: 'saudi', text: 'ما هو المهرجان الثقافي الأشهر في السعودية؟', options: ['مهرجان الجنادرية', 'موسم الرياض', 'موسم جدة', 'شتاء طنطورة'], correctIndex: 0 },
  { id: 674, category: 'saudi', text: 'ما هي الشركة السعودية الأكبر في العالم في مجال النفط؟', options: ['أرامكو', 'سابك', 'معادن', 'stc'], correctIndex: 0 },
  { id: 675, category: 'saudi', text: 'ما هي المدينة التي تشتهر بمهرجان التمور؟', options: ['بريدة', 'الخرج', 'الأحساء', 'عنيزة'], correctIndex: 0 },
  { id: 676, category: 'saudi', text: 'ما هو البرج الأطول في السعودية؟', options: ['برج المملكة', 'برج الفيصلية', 'برج الساعة', 'برج جدة'], correctIndex: 2 },
  { id: 677, category: 'saudi', text: 'ما هي المنطقة التي تشتهر بالجبال الخضراء؟', options: ['عسير', 'نجرين', 'جازان', 'الباحة'], correctIndex: 0 },
  { id: 678, category: 'saudi', text: 'ما هو المشروب الشعبي الأول في السعودية؟', options: ['القهوة العربية', 'الشاي', 'اللبن', 'العصير'], correctIndex: 0 },
  { id: 679, category: 'saudi', text: 'ما هي المدينة التي تقع فيها جامعة الملك فهد للبترول والمعادن؟', options: ['الظهران', 'الدمام', 'الخبر', 'الجبيل'], correctIndex: 0 },
  { id: 680, category: 'saudi', text: 'ما هي الصحراء الكبرى في جنوب السعودية؟', options: ['الربع الخالي', 'النفود الكبير', 'الدهناء', 'الصمان'], correctIndex: 0 },

  // تكنولوجيا (30 سؤال)
  { id: 701, category: 'technology', text: 'ما هي الشركة التي أنتجت نظام ويندوز؟', options: ['مايكروسوفت', 'آبل', 'غوغل', 'IBM'], correctIndex: 0 },
  { id: 702, category: 'technology', text: 'ما هو اختصار الشبكة العنكبوتية العالمية؟', options: ['WWW', 'HTTP', 'URL', 'HTML'], correctIndex: 0 },
  { id: 703, category: 'technology', text: 'من هو مؤسس شركة فيسبوك؟', options: ['مارك زوكربيرغ', 'إيلون ماسك', 'بيل غيتس', 'ستيف جوبز'], correctIndex: 0 },
  { id: 704, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لتحويل الإشارات الرقمية؟', options: ['المودم', 'الراوتر', 'السويتش', 'الهب'], correctIndex: 0 },
  { id: 705, category: 'technology', text: 'ما هي اللغة الأساسية لتصميم صفحات الويب؟', options: ['HTML', 'Java', 'Python', 'C++'], correctIndex: 0 },
  { id: 706, category: 'technology', text: 'ما هي الشركة التي أنتجت آيفون؟', options: ['آبل', 'سامسونج', 'هواوي', 'شاومي'], correctIndex: 0 },
  { id: 707, category: 'technology', text: 'ما هو اختصار الذكاء الاصطناعي؟', options: ['AI', 'VR', 'AR', 'IoT'], correctIndex: 0 },
  { id: 708, category: 'technology', text: 'ما هو النظام المستخدم في هواتف سامسونج؟', options: ['أندرويد', 'iOS', 'ويندوز فون', 'سيمبيان'], correctIndex: 0 },
  { id: 709, category: 'technology', text: 'ما هي وحدة قياس سرعة المعالج؟', options: ['جيجاهرتز', 'جيجابايت', 'ميجابكسل', 'فولت'], correctIndex: 0 },
  { id: 710, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لإدخال البيانات للكمبيوتر؟', options: ['لوحة المفاتيح', 'الشاشة', 'المعالج', 'الذاكرة'], correctIndex: 0 },
  { id: 711, category: 'technology', text: 'ما هي الشركة التي تملك يوتيوب؟', options: ['غوغل', 'فيسبوك', 'أمازون', 'آبل'], correctIndex: 0 },
  { id: 712, category: 'technology', text: 'ما هو اختصار البريد الإلكتروني؟', options: ['E-mail', 'G-mail', 'H-mail', 'I-mail'], correctIndex: 0 },
  { id: 713, category: 'technology', text: 'ما هي العملة الرقمية الأشهر؟', options: ['بيتكوين', 'إيثريوم', 'ريبل', 'لايتكوين'], correctIndex: 0 },
  { id: 714, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لتخزين البيانات؟', options: ['القرص الصلب', 'المعالج', 'الرام', 'الشاشة'], correctIndex: 0 },
  { id: 715, category: 'technology', text: 'ما هي الشركة التي تملك واتساب؟', options: ['فيسبوك (ميتا)', 'غوغل', 'مايكروسوفت', 'آبل'], correctIndex: 0 },
  { id: 716, category: 'technology', text: 'ما هو المتصفح الخاص بشركة غوغل؟', options: ['كروم', 'فايرفوكس', 'إيدج', 'سفاري'], correctIndex: 0 },
  { id: 717, category: 'technology', text: 'ما هو الجهاز الذي يستخدم للطباعة؟', options: ['الطابعة', 'الماسح الضوئي', 'الميكروفون', 'الكاميرا'], correctIndex: 0 },
  { id: 718, category: 'technology', text: 'ما هي اللغة المستخدمة في برمجة تطبيقات أندرويد؟', options: ['جافا', 'سويفت', 'بايثون', 'PHP'], correctIndex: 0 },
  { id: 719, category: 'technology', text: 'ما هو اختصار نظام تحديد المواقع؟', options: ['GPS', 'GPRS', 'GSM', 'LTE'], correctIndex: 0 },
  { id: 720, category: 'technology', text: 'ما هي الشركة التي أنتجت بلايستيشن؟', options: ['سوني', 'مايكروسوفت', 'نينتندو', 'سيجا'], correctIndex: 0 },
  { id: 721, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لتوجيه البيانات في الشبكات؟', options: ['الراوتر', 'المودم', 'السويتش', 'الهب'], correctIndex: 0 },
  { id: 722, category: 'technology', text: 'ما هي الشركة التي تملك إنستغرام؟', options: ['فيسبوك (ميتا)', 'غوغل', 'سناب شات', 'تيك توك'], correctIndex: 0 },
  { id: 723, category: 'technology', text: 'ما هو اختصار الواقع الافتراضي؟', options: ['VR', 'AR', 'AI', 'MR'], correctIndex: 0 },
  { id: 724, category: 'technology', text: 'ما هي الشركة التي أنتجت إكس بوكس؟', options: ['مايكروسوفت', 'سوني', 'نينتندو', 'سيجا'], correctIndex: 0 },
  { id: 725, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لالتقاط الصور؟', options: ['الكاميرا', 'الماسح الضوئي', 'الطابعة', 'السماعة'], correctIndex: 0 },
  { id: 726, category: 'technology', text: 'ما هي اللغة المستخدمة في برمجة تطبيقات iOS؟', options: ['سويفت', 'جافا', 'كوتلن', 'C#'], correctIndex: 0 },
  { id: 727, category: 'technology', text: 'ما هو اختصار ذاكرة الوصول العشوائي؟', options: ['RAM', 'ROM', 'CPU', 'GPU'], correctIndex: 0 },
  { id: 728, category: 'technology', text: 'ما هي الشركة التي أنتجت معالجات إنتل؟', options: ['إنتل', 'amd', 'nvidia', 'qualcomm'], correctIndex: 0 },
  { id: 729, category: 'technology', text: 'ما هو الجهاز الذي يستخدم لعرض الصور؟', options: ['الشاشة', 'الماوس', 'الكيبورد', 'السماعة'], correctIndex: 0 },
  { id: 730, category: 'technology', text: 'ما هي الشركة التي تملك تويتر (إكس) حالياً؟', options: ['إيلون ماسك', 'جاك دورسي', 'مارك زوكربيرغ', 'بيل غيتس'], correctIndex: 0 },

  // موسيقى وفنون (30 سؤال)
  { id: 751, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية القدر"؟', options: ['بيتهوفن', 'موزارت', 'باخ', 'شوبان'], correctIndex: 0 },
  { id: 752, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "ملكة الآلات"؟', options: ['الكمان', 'البيانو', 'القيثارة', 'الناي'], correctIndex: 0 },
  { id: 753, category: 'music', text: 'من هو الفنان الذي رسم "الموناليزا"؟', options: ['ليوناردو دا فينشي', 'فان غوخ', 'بيكاسو', 'مونيه'], correctIndex: 0 },
  { id: 754, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في الأرجنتين؟', options: ['التانغو', 'السالسا', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 755, category: 'music', text: 'من هو الموسيقار الذي ألف "فصل الربيع"؟', options: ['فيفالدي', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 756, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة العواطف"؟', options: ['الكمان', 'البيانو', 'القيثارة', 'الناي'], correctIndex: 0 },
  { id: 757, category: 'music', text: 'من هو الفنان الذي رسم "ليلة النجوم"؟', options: ['فان غوخ', 'ليوناردو دا فينشي', 'بيكاسو', 'مونيه'], correctIndex: 0 },
  { id: 758, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في إسبانيا؟', options: ['الفلامنكو', 'التانغو', 'السالسا', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 759, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية الجنوب"؟', options: ['ديفوراك', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 760, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة الرياح"؟', options: ['الناي', 'الكمان', 'البيانو', 'القيثارة'], correctIndex: 0 },
  { id: 761, category: 'music', text: 'من هو الفنان الذي رسم "الصرخة"؟', options: ['مونش', 'فان غوخ', 'ليوناردو دا فينشي', 'بيكاسو'], correctIndex: 0 },
  { id: 762, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في البرازيل؟', options: ['السامبا', 'التانغو', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 763, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية الألف"؟', options: ['مالر', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 764, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة الإيقاع"؟', options: ['الطبلة', 'الكمان', 'البيانو', 'القيثارة'], correctIndex: 0 },
  { id: 765, category: 'music', text: 'من هو الفنان الذي رسم "غرنيكا"؟', options: ['بيكاسو', 'فان غوخ', 'ليوناردو دا فينشي', 'مونيه'], correctIndex: 0 },
  { id: 766, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في كوبا؟', options: ['السالسا', 'التانغو', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 767, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية الرعب"؟', options: ['باربر', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 768, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة الوتر"؟', options: ['القيثارة', 'الكمان', 'البيانو', 'الناي'], correctIndex: 0 },
  { id: 769, category: 'music', text: 'من هو الفنان الذي رسم "العشاء الأخير"؟', options: ['ليوناردو دا فينشي', 'فان غوخ', 'بيكاسو', 'مونيه'], correctIndex: 0 },
  { id: 770, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في الهند؟', options: ['البهاراتناتيام', 'التانغو', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 771, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية الطبيعة"؟', options: ['هايدن', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 772, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة النفخ"؟', options: ['الناي', 'الكمان', 'البيانو', 'القيثارة'], correctIndex: 0 },
  { id: 773, category: 'music', text: 'من هو الفنان الذي رسم "ولادة فينوس"؟', options: ['بوتيتشيلي', 'فان غوخ', 'ليوناردو دا فينشي', 'بيكاسو'], correctIndex: 0 },
  { id: 774, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في اليابان؟', options: ['الكابوكي', 'التانغو', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 775, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية البطل"؟', options: ['بيتهوفن', 'موزارت', 'باخ', 'شوبان'], correctIndex: 0 },
  { id: 776, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة الإيقاع"؟', options: ['الطبلة', 'الكمان', 'البيانو', 'القيثارة'], correctIndex: 0 },
  { id: 777, category: 'music', text: 'من هو الفنان الذي رسم "حاملة الخبز"؟', options: ['ميلو', 'فان غوخ', 'ليوناردو دا فينشي', 'بيكاسو'], correctIndex: 0 },
  { id: 778, category: 'music', text: 'ما هي الرقصة الشهيرة التي نشأت في فرنسا؟', options: ['الكانكان', 'التانغو', 'الفلامنكو', 'الرقص الشرقي'], correctIndex: 0 },
  { id: 779, category: 'music', text: 'من هو الموسيقار الذي ألف "سمفونية القمر"؟', options: ['ديبوسي', 'بيتهوفن', 'موزارت', 'باخ'], correctIndex: 0 },
  { id: 780, category: 'music', text: 'ما هي الآلة الموسيقية المعروفة باسم "آلة الوتر"؟', options: ['القيثارة', 'الكمان', 'البيانو', 'الناي'], correctIndex: 0 },

  // جغرافيا وسفر (30 سؤال)
  { id: 801, category: 'geography', text: 'ما هي أكبر قارة في العالم؟', options: ['آسيا', 'أفريقيا', 'أوروبا', 'أمريكا الشمالية'], correctIndex: 0 },
  { id: 802, category: 'geography', text: 'ما هو أطول نهر في العالم؟', options: ['نهر النيل', 'نهر الأمازون', 'نهر المسيسيبي', 'نهر اليانغتسي'], correctIndex: 0 },
  { id: 803, category: 'geography', text: 'ما هي أعلى قمة في العالم؟', options: ['جبل إفرست', 'جبل كي 2', 'جبل كانغشينجونغا', 'جبل لوتسي'], correctIndex: 0 },
  { id: 804, category: 'geography', text: 'ما هي أكبر محيط في العالم؟', options: ['المحيط الهادئ', 'المحيط الأطلسي', 'المحيط الهندي', 'المحيط المتجمد الشمالي'], correctIndex: 0 },
  { id: 805, category: 'geography', text: 'ما هي أكبر دولة في العالم من حيث المساحة؟', options: ['روسيا', 'كندا', 'الولايات المتحدة', 'الصين'], correctIndex: 0 },
  { id: 806, category: 'geography', text: 'ما هي أصغر دولة في العالم؟', options: ['الفاتيكان', 'موناكو', 'ناورو', 'توفالو'], correctIndex: 0 },
  { id: 807, category: 'geography', text: 'ما هي أكبر صحراء في العالم؟', options: ['الصحراء الكبرى', 'صحراء الربع الخالي', 'صحراء جوبي', 'صحراء كالاهاري'], correctIndex: 0 },
  { id: 808, category: 'geography', text: 'ما هي أطول سلسلة جبال في العالم؟', options: ['جبال الأنديز', 'جبال الهيمالايا', 'جبال روكي', 'جبال الألب'], correctIndex: 0 },
  { id: 809, category: 'geography', text: 'ما هي أكبر جزيرة في العالم؟', options: ['جرينلاند', 'مدغشقر', 'بورنيو', 'بابوا غينيا الجديدة'], correctIndex: 0 },
  { id: 810, category: 'geography', text: 'ما هي أكبر مدينة في العالم من حيث عدد السكان؟', options: ['طوكيو', 'دلهي', 'شنغهاي', 'مكسيكو سيتي'], correctIndex: 0 },
  { id: 811, category: 'geography', text: 'ما هي عاصمة اليابان؟', options: ['طوكيو', 'كيوتو', 'أوساكا', 'نارا'], correctIndex: 0 },
  { id: 812, category: 'geography', text: 'ما هي الدولة التي تشبه شكل الحذاء؟', options: ['إيطاليا', 'اليونان', 'إسبانيا', 'فرنسا'], correctIndex: 0 },
  { id: 813, category: 'geography', text: 'ما هو النهر الذي يمر عبر القاهرة؟', options: ['نهر النيل', 'نهر الفرات', 'نهر دجلة', 'نهر الأمازون'], correctIndex: 0 },
  { id: 814, category: 'geography', text: 'ما هي أكبر بحيرة في العالم؟', options: ['بحر قزوين', 'بحيرة فيكتوريا', 'بحيرة سوبيريور', 'بحيرة بايكال'], correctIndex: 0 },
  { id: 815, category: 'geography', text: 'ما هي الدولة التي تقع فيها مدينة البتراء؟', options: ['الأردن', 'سوريا', 'لبنان', 'العراق'], correctIndex: 0 },
  { id: 816, category: 'geography', text: 'ما هي عاصمة المملكة المتحدة؟', options: ['لندن', 'باريس', 'برلين', 'مدريد'], correctIndex: 0 },
  { id: 817, category: 'geography', text: 'ما هي القارة التي يقع فيها القطب الجنوبي؟', options: ['أنتاركتيكا', 'آسيا', 'أوروبا', 'أمريكا الجنوبية'], correctIndex: 0 },
  { id: 818, category: 'geography', text: 'ما هي الدولة التي تشتهر بالأهرامات؟', options: ['مصر', 'السودان', 'المكسيك', 'بيرو'], correctIndex: 0 },
  { id: 819, category: 'geography', text: 'ما هي أكبر دولة في أفريقيا من حيث المساحة؟', options: ['الجزائر', 'نيجيريا', 'مصر', 'جنوب أفريقيا'], correctIndex: 0 },
  { id: 820, category: 'geography', text: 'ما هي عاصمة كندا؟', options: ['أوتاوا', 'تورونتو', 'فانكوفر', 'مونتريال'], correctIndex: 0 },
  { id: 821, category: 'geography', text: 'ما هي الدولة التي تقع فيها مدينة البندقية؟', options: ['إيطاليا', 'فرنسا', 'إسبانيا', 'اليونان'], correctIndex: 0 },
  { id: 822, category: 'geography', text: 'ما هو النهر الذي يمر عبر بغداد؟', options: ['نهر دجلة', 'نهر الفرات', 'نهر النيل', 'نهر الأردن'], correctIndex: 0 },
  { id: 823, category: 'geography', text: 'ما هي عاصمة ألمانيا؟', options: ['برلين', 'ميونخ', 'هامبورغ', 'فرانكفورت'], correctIndex: 0 },
  { id: 824, category: 'geography', text: 'ما هي الدولة التي تشتهر بزهرة التوليب؟', options: ['هولندا', 'فرنسا', 'بلجيكا', 'ألمانيا'], correctIndex: 0 },
  { id: 825, category: 'geography', text: 'ما هي أكبر مدينة في الولايات المتحدة؟', options: ['نيويورك', 'لوس أنجلوس', 'شيكاغو', 'هيوستن'], correctIndex: 0 },
  { id: 826, category: 'geography', text: 'ما هي عاصمة الصين؟', options: ['بكين', 'شنغهاي', 'غوانزو', 'شينزين'], correctIndex: 0 },
  { id: 827, category: 'geography', text: 'ما هي الدولة التي تقع فيها مدينة مكة؟', options: ['السعودية', 'الإمارات', 'الكويت', 'قطر'], correctIndex: 0 },
  { id: 828, category: 'geography', text: 'ما هو النهر الذي يمر عبر لندن؟', options: ['نهر التايمز', 'نهر السين', 'نهر الراين', 'نهر الدانوب'], correctIndex: 0 },
  { id: 829, category: 'geography', text: 'ما هي عاصمة روسيا؟', options: ['موسكو', 'سانت بطرسبرغ', 'كييف', 'مينسك'], correctIndex: 0 },
  { id: 830, category: 'geography', text: 'ما هي الدولة التي تقع فيها مدينة دبي؟', options: ['الإمارات', 'السعودية', 'قطر', 'الكويت'], correctIndex: 0 },

  // طعام وطبخ (30 سؤال)
  { id: 851, category: 'food', text: 'ما هو الطبق الوطني لإيطاليا؟', options: ['البيتزا', 'المعكرونة', 'اللازانيا', 'الرافيولي'], correctIndex: 0 },
  { id: 852, category: 'food', text: 'ما هو المكون الرئيسي في الحمص؟', options: ['الحمص', 'الطحينة', 'الليمون', 'الثوم'], correctIndex: 0 },
  { id: 853, category: 'food', text: 'ما هو الطبق الوطني للمكسيك؟', options: ['التاكو', 'البروتو', 'الإنشلادة', 'الغواكامولي'], correctIndex: 0 },
  { id: 854, category: 'food', text: 'ما هو المكون الرئيسي في السوشي؟', options: ['الأرز', 'السمك', 'الأعشاب البحرية', 'الخضار'], correctIndex: 0 },
  { id: 855, category: 'food', text: 'ما هو الطبق الوطني للهند؟', options: ['الكاري', 'البرياني', 'التندوري', 'الساموسا'], correctIndex: 0 },
  { id: 856, category: 'food', text: 'ما هو المكون الرئيسي في البيتزا؟', options: ['العجين', 'الجبن', 'الطماطم', 'البيبروني'], correctIndex: 0 },
  { id: 857, category: 'food', text: 'ما هو الطبق الوطني لليابان؟', options: ['السوشي', 'الرامن', 'التيمبورا', 'الساشيمي'], correctIndex: 0 },
  { id: 858, category: 'food', text: 'ما هو المكون الرئيسي في الكبسة؟', options: ['الأرز', 'اللحم', 'البهارات', 'الزبيب'], correctIndex: 0 },
  { id: 859, category: 'food', text: 'ما هو الطبق الوطني للصين؟', options: ['البط البكيني', 'الديم سم', 'الزلابية', 'الأرز المقلي'], correctIndex: 0 },
  { id: 860, category: 'food', text: 'ما هو المكون الرئيسي في الشوكولاتة؟', options: ['الكاكاو', 'السكر', 'الحليب', 'الزبدة'], correctIndex: 0 },
  { id: 861, category: 'food', text: 'ما هو الطبق الوطني لفرنسا؟', options: ['الكرواسون', 'الباجيت', 'الحلزون', 'الفوا جرا'], correctIndex: 0 },
  { id: 862, category: 'food', text: 'ما هو المكون الرئيسي في الفلافل؟', options: ['الحمص', 'الفول', 'البقدونس', 'البصل'], correctIndex: 0 },
  { id: 863, category: 'food', text: 'ما هو الطبق الوطني لأسبانيا؟', options: ['الباييلا', 'التاباس', 'التورتيلا', 'الجازباتشو'], correctIndex: 0 },
  { id: 864, category: 'food', text: 'ما هو المكون الرئيسي في الكنافة؟', options: ['الجبن', 'السميد', 'السكر', 'القشطة'], correctIndex: 0 },
  { id: 865, category: 'food', text: 'ما هو الطبق الوطني لتركيا؟', options: ['الكباب', 'الدونر', 'البقلاوة', 'الكفتة'], correctIndex: 0 },
  { id: 866, category: 'food', text: 'ما هو المكون الرئيسي في المعمول؟', options: ['التمر', 'الفستق', 'الجوز', 'اللوز'], correctIndex: 0 },
  { id: 867, category: 'food', text: 'ما هو الطبق الوطني لتايلاند؟', options: ['باد تاي', 'توم يام', 'الكاري الأخضر', 'الأرز المقلي'], correctIndex: 0 },
  { id: 868, category: 'food', text: 'ما هو المكون الرئيسي في البسبوسة؟', options: ['السميد', 'السكر', 'اللبن', 'جوز الهند'], correctIndex: 0 },
  { id: 869, category: 'food', text: 'ما هو الطبق الوطني للمغرب؟', options: ['الكسكس', 'الطاجين', 'الحريرة', 'البسطيلة'], correctIndex: 0 },
  { id: 870, category: 'food', text: 'ما هو المكون الرئيسي في المهلبية؟', options: ['الحليب', 'النشا', 'السكر', 'ماء الورد'], correctIndex: 0 },
  { id: 871, category: 'food', text: 'ما هو الطبق الوطني للبنان؟', options: ['التبولة', 'الكبة', 'الفتوش', 'الحمص'], correctIndex: 0 },
  { id: 872, category: 'food', text: 'ما هو المكون الرئيسي في المنسف؟', options: ['الجميد', 'اللحم', 'الأرز', 'الخبز'], correctIndex: 0 },
  { id: 873, category: 'food', text: 'ما هو الطبق الوطني لمصر؟', options: ['الكشري', 'الفول', 'الطعمية', 'الملوخية'], correctIndex: 0 },
  { id: 874, category: 'food', text: 'ما هو المكون الرئيسي في أم علي؟', options: ['الرقاق', 'الحليب', 'المكسرات', 'القشطة'], correctIndex: 0 },
  { id: 875, category: 'food', text: 'ما هو الطبق الوطني لليونان؟', options: ['الموساكا', 'السوفلاكي', 'السلطة اليونانية', 'الجبن الفيتا'], correctIndex: 0 },
  { id: 876, category: 'food', text: 'ما هو المكون الرئيسي في البشاميل؟', options: ['الحليب', 'الدقيق', 'الزبدة', 'البيض'], correctIndex: 0 },
  { id: 877, category: 'food', text: 'ما هو الطبق الوطني لأمريكا؟', options: ['الهمبرغر', 'الهوت دوج', 'الفطيرة', 'الستيك'], correctIndex: 0 },
  { id: 878, category: 'food', text: 'ما هو المكون الرئيسي في التشيز كيك؟', options: ['الجبن الكريمي', 'البسكويت', 'السكر', 'البيض'], correctIndex: 0 },
  { id: 879, category: 'food', text: 'ما هو الطبق الوطني لروسيا؟', options: ['البورش', 'البليني', 'السترودل', 'البيف ستروجانوف'], correctIndex: 0 },
  { id: 880, category: 'food', text: 'ما هو المكون الرئيسي في الكريب؟', options: ['الدقيق', 'الحليب', 'البيض', 'السكر'], correctIndex: 0 },

  // شخصيات عالمية (30 سؤال)
  { id: 901, category: 'people', text: 'من هو العالم الذي اكتشف الجاذبية؟', options: ['إسحاق نيوتن', 'ألبرت أينشتاين', 'غاليليو غاليلي', 'نيكولا تيسلا'], correctIndex: 0 },
  { id: 902, category: 'people', text: 'من هو مؤسس شركة مايكروسوفت؟', options: ['بيل غيتس', 'ستيف جوبز', 'مارك زوكربيرغ', 'لاري بيج'], correctIndex: 0 },
  { id: 903, category: 'people', text: 'من هو الفنان الذي رسم لوحة "الموناليزا"؟', options: ['ليوناردو دا فينشي', 'فان غوخ', 'بابلو بيكاسو', 'كلود مونيه'], correctIndex: 0 },
  { id: 904, category: 'people', text: 'من هو القائد العسكري الذي غزا معظم أوروبا؟', options: ['نابليون بونابرت', 'يوليوس قيصر', 'الإسكندر الأكبر', 'هانيبال'], correctIndex: 0 },
  { id: 905, category: 'people', text: 'من هو العالم الذي طور نظرية النسبية؟', options: ['ألبرت أينشتاين', 'إسحاق نيوتن', 'ستيفن هوكينج', 'نيلز بور'], correctIndex: 0 },
  { id: 906, category: 'people', text: 'من هو المخترع الذي اخترع المصباح الكهربائي؟', options: ['توماس إديسون', 'نيكولا تيسلا', 'ألكسندر غراهام بيل', 'هنري فورد'], correctIndex: 0 },
  { id: 907, category: 'people', text: 'من هو الكاتب الذي كتب مسرحية "روميو وجولييت"؟', options: ['ويليام شكسبير', 'أرثر كونان دويل', 'تشارلز ديكنز', 'مارك توين'], correctIndex: 0 },
  { id: 908, category: 'people', text: 'من هو العالم الذي اكتشف البنسلين؟', options: ['ألكسندر فلمنج', 'لويس باستور', 'روبرت كوخ', 'ماري كوري'], correctIndex: 0 },
  { id: 909, category: 'people', text: 'من هو القائد الذي حرر الهند من الاستعمار البريطاني؟', options: ['المهاتما غاندي', 'جواهر لال نهرو', 'سوبهاس تشاندرا بوس', 'أبو الكلام آزاد'], correctIndex: 0 },
  { id: 910, category: 'people', text: 'من هو الفنان الذي ألف سمفونية "القدر"؟', options: ['لودفيغ فان بيتهوفن', 'فولفغانغ أماديوس موزارت', 'يوهان سباستيان باخ', 'بيتر إليتش تشايكوفسكي'], correctIndex: 0 },
  { id: 911, category: 'people', text: 'من هو العالم الذي طور لقاح شلل الأطفال؟', options: ['جوناس سالك', 'لويس باستور', 'روبرت كوخ', 'إدوارد جينر'], correctIndex: 0 },
  { id: 912, category: 'people', text: 'من هو المخترع الذي اخترع الهاتف؟', options: ['ألكسندر غراهام بيل', 'توماس إديسون', 'نيكولا تيسلا', 'غولييلمو ماركوني'], correctIndex: 0 },
  { id: 913, category: 'people', text: 'من هو الكاتب الذي كتب رواية "البؤساء"؟', options: ['فيكتور هوغو', 'أونوريه دي بلزاك', 'غوستاف فلوبير', 'إميل زولا'], correctIndex: 0 },
  { id: 914, category: 'people', text: 'من هو العالم الذي اكتشف الأشعة السينية؟', options: ['فيلهلم كونراد رونتغن', 'ماري كوري', 'هنري بيكريل', 'إرنست رذرفورد'], correctIndex: 0 },
  { id: 915, category: 'people', text: 'من هو القائد الذي قاد الثورة الروسية؟', options: ['فلاديمير لينين', 'ليون تروتسكي', 'جوزيف ستالين', 'نيكولاي الثاني'], correctIndex: 0 },
  { id: 916, category: 'people', text: 'من هو الفنان الذي رسم لوحة "ليلة النجوم"؟', options: ['فنسنت فان غوخ', 'ليوناردو دا فينشي', 'بابلو بيكاسو', 'كلود مونيه'], correctIndex: 0 },
  { id: 917, category: 'people', text: 'من هو العالم الذي طور نظرية التطور؟', options: ['تشارلز داروين', 'ألفرد راسل والاس', 'غريغور مندل', 'كارل لينيوس'], correctIndex: 0 },
  { id: 918, category: 'people', text: 'من هو المخترع الذي اخترع الطائرة؟', options: ['الأخوان رايت', 'غيومو ماركوني', 'نيكولا تيسلا', 'هنري فورد'], correctIndex: 0 },
  { id: 919, category: 'people', text: 'من هو الكاتب الذي كتب مسرحية "هاملت"؟', options: ['ويليام شكسبير', 'أرثر ميلر', 'تينيسي وليامز', 'صمويل بيكيت'], correctIndex: 0 },
  { id: 920, category: 'people', text: 'من هو العالم الذي اكتشف البنية الحلزونية للحمض النووي؟', options: ['جيمس واطسون وفرانسيس كريك', 'روزاليند فرانكلين', 'ماوريس ويلكينز', 'لينوس باولنغ'], correctIndex: 0 },
  { id: 921, category: 'people', text: 'من هو القائد الذي أسس الإمبراطورية المغولية؟', options: ['جنكيز خان', 'قوبلاي خان', 'تيمورلنك', 'أبو بكر'], correctIndex: 0 },
  { id: 922, category: 'people', text: 'من هو الفنان الذي ألف سمفونية "الأميرة النائمة"؟', options: ['بيتر إليتش تشايكوفسكي', 'لودفيغ فان بيتهوفن', 'فولفغانغ أماديوس موزارت', 'يوهان شتراوس'], correctIndex: 0 },
  { id: 923, category: 'people', text: 'من هو العالم الذي اكتشف الدورة الدموية؟', options: ['ويليام هارفي', 'أندرياس فيزاليوس', 'كلود برنار', 'لويس باستور'], correctIndex: 0 },
  { id: 924, category: 'people', text: 'من هو المخترع الذي اخترع المطبعة؟', options: ['يوهانس غوتنبرغ', 'جيمس واط', 'إسحاق نيوتن', 'غاليليو غاليلي'], correctIndex: 0 },
  { id: 925, category: 'people', text: 'من هو الكاتب الذي كتب رواية "الحرب والسلام"؟', options: ['ليو تولستوي', 'فيودور دوستويفسكي', 'أنطون تشيخوف', 'ألكسندر بوشكين'], correctIndex: 0 },
  { id: 926, category: 'people', text: 'من هو العالم الذي اكتشف النشاط الإشعاعي؟', options: ['هنري بيكريل', 'ماري كوري', 'إرنست رذرفورد', 'نيلز بور'], correctIndex: 0 },
  { id: 927, category: 'people', text: 'من هو القائد الذي قاد حركة الحقوق المدنية في الولايات المتحدة؟', options: ['مارتن لوثر كينغ جونيور', 'مالكوم إكس', 'روزا باركس', 'جون إف كينيدي'], correctIndex: 0 },
  { id: 928, category: 'people', text: 'من هو الفنان الذي رسم لوحة "غرنيكا"؟', options: ['بابلو بيكاسو', 'سلفادور دالي', 'رينيه ماغريت', 'فريدا كاهلو'], correctIndex: 0 },
  { id: 929, category: 'people', text: 'من هو العالم الذي طور ميكانيكا الكم؟', options: ['ماكس بلانك', 'ألبرت أينشتاين', 'نيلز بور', 'فيرنر هايزنبرغ'], correctIndex: 0 },
  { id: 930, category: 'people', text: 'من هو المخترع الذي اخترع الديناميت؟', options: ['ألفريد نوبل', 'توماس إديسون', 'نيكولا تيسلا', 'جيمس واط'], correctIndex: 0 },

];

// ==========================================
// Game Constants (Unchanged)
// ==========================================
export const BOSS_DATA = {
  initialHP: 5000,
  name: 'الغول العملاق',
  image: '👹'
};

export const FLAGS_DATA = [
  // --- ARAB WORLD (EASY) ---
  { code: 'sa', names: ['السعودية', 'المملكة العربية السعودية', 'Saudi Arabia'] },
  { code: 'kw', names: ['الكويت', 'Kuwait'] },
  { code: 'ae', names: ['الامارات', 'الإمارات', 'UAE'] },
  { code: 'qa', names: ['قطر', 'Qatar'] },
  { code: 'om', names: ['عمان', 'Oman'] },
  { code: 'bh', names: ['البحرين', 'Bahrain'] },
  { code: 'eg', names: ['مصر', 'Egypt'] },
  { code: 'ma', names: ['المغرب', 'Morocco'] },
  { code: 'dz', names: ['الجزائر', 'Algeria'] },
  { code: 'tn', names: ['تونس', 'Tunisia'] },
  { code: 'iq', names: ['العراق', 'Iraq'] },
  { code: 'ps', names: ['فلسطين', 'Palestine'] },
  { code: 'lb', names: ['لبنان', 'Lebanon'] },
  { code: 'jo', names: ['الاردن', 'الأردن', 'Jordan'] },
  { code: 'sy', names: ['سوريا', 'Syria'] },
  { code: 'ye', names: ['اليمن', 'Yemen'] },
  { code: 'sd', names: ['السودان', 'Sudan'] },
  { code: 'ly', names: ['ليبيا', 'Libya'] },
  { code: 'mr', names: ['موريتانيا', 'Mauritania'] },
  { code: 'so', names: ['الصومال', 'Somalia'] },
  { code: 'dj', names: ['جيبوتي', 'Djibouti'] },
  { code: 'km', names: ['جزر القمر', 'Comoros'] },

  // --- FAMOUS WORLD (MEDIUM) ---
  { code: 'us', names: ['امريكا', 'الولايات المتحدة', 'USA'] },
  { code: 'gb', names: ['بريطانيا', 'المملكة المتحدة', 'UK'] },
  { code: 'fr', names: ['فرنسا', 'France'] },
  { code: 'de', names: ['المانيا', 'ألمانيا', 'Germany'] },
  { code: 'it', names: ['ايطاليا', 'إيطاليا', 'Italy'] },
  { code: 'es', names: ['اسبانيا', 'إسبانيا', 'Spain'] },
  { code: 'jp', names: ['اليابان', 'Japan'] },
  { code: 'cn', names: ['الصين', 'China'] },
  { code: 'ru', names: ['روسيا', 'Russia'] },
  { code: 'in', names: ['الهند', 'India'] },
  { code: 'br', names: ['البرازيل', 'Brazil'] },
  { code: 'ar', names: ['الارجنتين', 'الأرجنتين', 'Argentina'] },
  { code: 'ca', names: ['كندا', 'Canada'] },
  { code: 'au', names: ['استراليا', 'أستراليا', 'Australia'] },
  { code: 'tr', names: ['تركيا', 'Turkey'] },
  { code: 'kr', names: ['كوريا الجنوبية', 'South Korea'] },
  { code: 'kp', names: ['كوريا الشمالية', 'North Korea'] },
  { code: 'id', names: ['اندونيسيا', 'إندونيسيا', 'Indonesia'] },
  { code: 'my', names: ['ماليزيا', 'Malaysia'] },
  { code: 'th', names: ['تايلاند', 'Thailand'] },
  { code: 'vn', names: ['فيتنام', 'Vietnam'] },
  { code: 'ph', names: ['الفلبين', 'Philippines'] },
  { code: 'pk', names: ['باكستان', 'Pakistan'] },
  { code: 'ir', names: ['ايران', 'إيران', 'Iran'] },
  { code: 'af', names: ['افغانستان', 'أفغانستان', 'Afghanistan'] },
  { code: 'mx', names: ['المكسيك', 'Mexico'] },
  { code: 'za', names: ['جنوب افريقيا', 'South Africa'] },
  { code: 'ng', names: ['نيجيريا', 'Nigeria'] },
  { code: 'et', names: ['اثيوبيا', 'إثيوبيا', 'Ethiopia'] },
  { code: 'ke', names: ['كينيا', 'Kenya'] },
  { code: 'gh', names: ['غانا', 'Ghana'] },
  { code: 'cm', names: ['الكاميرون', 'Cameroon'] },
  { code: 'sn', names: ['السنغال', 'Senegal'] },
  { code: 'pt', names: ['البرتغال', 'Portugal'] },
  { code: 'nl', names: ['هولندا', 'Netherlands'] },
  { code: 'be', names: ['بلجيكا', 'Belgium'] },
  { code: 'ch', names: ['سويسرا', 'Switzerland'] },
  { code: 'at', names: ['النمسا', 'Austria'] },
  { code: 'se', names: ['السويد', 'Sweden'] },
  { code: 'no', names: ['النرويج', 'Norway'] },
  { code: 'dk', names: ['الدانمارك', 'الدنمارك', 'Denmark'] },
  { code: 'fi', names: ['فنلندا', 'Finland'] },
  { code: 'pl', names: ['بولندا', 'Poland'] },
  { code: 'ua', names: ['اوكرانيا', 'أوكرانيا', 'Ukraine'] },
  { code: 'gr', names: ['اليونان', 'Greece'] },
  { code: 'hr', names: ['كرواتيا', 'Croatia'] },
  { code: 'rs', names: ['صربيا', 'Serbia'] },
  { code: 'ro', names: ['رومانيا', 'Romania'] },
  { code: 'bg', names: ['بلغاريا', 'Bulgaria'] },
  { code: 'hu', names: ['المجر', 'هنجاريا', 'Hungary'] },
  { code: 'cz', names: ['التشيك', 'Czech'] },
  { code: 'ie', names: ['ايرلندا', 'أيرلندا', 'Ireland'] },
  { code: 'is', names: ['ايسلتدا', 'آيسلندا', 'Iceland'] },
  { code: 'nz', names: ['نيوزيلندا', 'New Zealand'] },
  { code: 'cl', names: ['تشيلي', 'Chile'] },
  { code: 'co', names: ['كولومبيا', 'Colombia'] },
  { code: 'pe', names: ['بيرو', 'Peru'] },
  { code: 've', names: ['فنزويلا', 'Venezuela'] },
  { code: 'uy', names: ['اوروغواي', 'Uruguay'] },
  { code: 'py', names: ['باراغواي', 'Paraguay'] },
  { code: 'bo', names: ['بوليفيا', 'Bolivia'] },
  { code: 'ec', names: ['الاكوادور', 'Ecuador'] },
  { code: 'cu', names: ['كوبا', 'Cuba'] },
  { code: 'jm', names: ['جاميكا', 'Jamaica'] },
  { code: 'pa', names: ['بنما', 'Panama'] },
  { code: 'cr', names: ['كوستاريكا', 'Costa Rica'] },

  // --- HARD / OBSCURE (HARD) ---
  { code: 'kz', names: ['كازاخستان', 'Kazakhstan'] },
  { code: 'uz', names: ['اوزبكستان', 'أوزبكستان', 'Uzbekistan'] },
  { code: 'tm', names: ['تركمانستان', 'Turkmenistan'] },
  { code: 'kg', names: ['قيرغيزستان', 'Kyrgyzstan'] },
  { code: 'tj', names: ['طاجيكستان', 'Tajikistan'] },
  { code: 'az', names: ['اذرينجان', 'أذربيجان', 'Azerbaijan'] },
  { code: 'am', names: ['ارمينيا', 'أرمينيا', 'Armenia'] },
  { code: 'ge', names: ['جورجيا', 'Georgia'] },
  { code: 'mn', names: ['منغوليا', 'Mongolia'] },
  { code: 'np', names: ['نيبال', 'Nepal'] },
  { code: 'lk', names: ['سريلانكا', 'Sri Lanka'] },
  { code: 'bd', names: ['بنغلاديش', 'Bangladesh'] },
  { code: 'mm', names: ['ميانمار', 'بورما', 'Myanmar'] },
  { code: 'la', names: ['لاوس', 'Laos'] },
  { code: 'kh', names: ['كمبوديا', 'Cambodia'] },
  { code: 'sg', names: ['سنغافورة', 'Singapore'] },
  { code: 'bn', names: ['بروناي', 'Brunei'] },
  { code: 'tl', names: ['تيمور الشرقية', 'Timor-Leste'] },
  { code: 'mv', names: ['المالديف', 'Maldives'] },
  { code: 'bt', names: ['بوتان', 'Bhutan'] },
  { code: 'ee', names: ['استونيا', 'Estonia'] },
  { code: 'lv', names: ['لاتفيا', 'Latvia'] },
  { code: 'lt', names: ['ليتوانيا', 'Lithuania'] },
  { code: 'by', names: ['بيلاروسيا', 'Belarus'] },
  { code: 'md', names: ['مولدوفا', 'Moldova'] },
  { code: 'sk', names: ['سلوفاكيا', 'Slovakia'] },
  { code: 'si', names: ['سلوفينيا', 'Slovenia'] },
  { code: 'ba', names: ['البوسنة', 'البوسنة والهرسك', 'Bosnia'] },
  { code: 'mk', names: ['مقدونيا', 'Macedonia'] },
  { code: 'al', names: ['البانيا', 'ألبانيا', 'Albania'] },
  { code: 'me', names: ['الجبل الأسود', 'مونتينيغرو', 'Montenegro'] },
  { code: 'xk', names: ['كوسوفو', 'Kosovo'] },
  { code: 'cy', names: ['قبرص', 'Cyprus'] },
  { code: 'mt', names: ['مالطا', 'Malta'] },
  { code: 'ad', names: ['اندورا', 'Andorra'] },
  { code: 'mc', names: ['موناكو', 'Monaco'] },
  { code: 'li', names: ['ليختنشتاين', 'Liechtenstein'] },
  { code: 'sm', names: ['سان مارينو', 'San Marino'] },
  { code: 'va', names: ['الفاتيكان', 'Vatican'] },
  { code: 'lu', names: ['لوكسمبورغ', 'Luxembourg'] },

  // --- EXTREMELY HARD (ISLANDS & AFRICA) ---
  { code: 'tv', names: ['توفالو', 'Tuvalu'] },
  { code: 'nr', names: ['ناورو', 'Nauru'] },
  { code: 'ki', names: ['كيريباتي', 'Kiribati'] },
  { code: 'mh', names: ['جزر مارشال', 'Marshall Islands'] },
  { code: 'pw', names: ['بالاو', 'Palau'] },
  { code: 'fm', names: ['ميكرونيزيا', 'Micronesia'] },
  { code: 'ws', names: ['ساموا', 'Samoa'] },
  { code: 'to', names: ['تونغا', 'Tonga'] },
  { code: 'vu', names: ['فانواتو', 'Vanuatu'] },
  { code: 'fj', names: ['فيجي', 'Fiji'] },
  { code: 'sb', names: ['جزر سليمان', 'Solomon Islands'] },
  { code: 'pg', names: ['بابوا غينيا الجديدة', 'Papua New Guinea'] },
  { code: 'cv', names: ['الرأس الاخضر', 'Cape Verde'] },
  { code: 'st', names: ['ساو تومي', 'Sao Tome'] },
  { code: 'sc', names: ['سيشل', 'Seychelles'] },
  { code: 'mu', names: ['موريشيوس', 'Mauritius'] },
  { code: 'mg', names: ['مدغشقر', 'Madagascar'] },
  { code: 'mz', names: ['موزمبيق', 'Mozambique'] },
  { code: 'zw', names: ['زيمبابوي', 'Zimbabwe'] },
  { code: 'zm', names: ['زامبيا', 'Zambia'] },
  { code: 'mw', names: ['ملاوي', 'Malawi'] },
  { code: 'tz', names: ['تنزانيا', 'Tanzania'] },
  { code: 'ug', names: ['اوغندا', 'أوغندا', 'Uganda'] },
  { code: 'rw', names: ['رواندا', 'Rwanda'] },
  { code: 'bi', names: ['بوروندي', 'Burundi'] },
  { code: 'cd', names: ['الكونغو الديمقراطية', 'DR Congo'] },
  { code: 'cg', names: ['الكونغو', 'Congo'] },
  { code: 'ga', names: ['الغابون', 'Gabon'] },
  { code: 'gq', names: ['غينيا الاستوائية', 'Equatorial Guinea'] },
  { code: 'cf', names: ['افريقيا الوسطى', 'Central African Republic'] },
  { code: 'td', names: ['تشاد', 'Chad'] },
  { code: 'ne', names: ['النيجر', 'Niger'] },
  { code: 'ml', names: ['مالي', 'Mali'] },
  { code: 'bf', names: ['بوركينا فاسو', 'Burkina Faso'] },
  { code: 'ci', names: ['ساحل العاج', 'Ivory Coast'] },
  { code: 'lr', names: ['ليبيريا', 'Liberia'] },
  { code: 'sl', names: ['سيراليون', 'Sierra Leone'] },
  { code: 'gn', names: ['غينيا', 'Guinea'] },
  { code: 'gw', names: ['غينيا بيساو', 'Guinea-Bissau'] },
  { code: 'gm', names: ['غامبيا', 'Gambia'] },
  { code: 'tg', names: ['توغو', 'Togo'] },
  { code: 'bj', names: ['بنين', 'Benin'] },
  { code: 'na', names: ['ناميبيا', 'Namibia'] },
  { code: 'bw', names: ['بوتسوانا', 'Botswana'] },
  { code: 'sz', names: ['اسواتيني', 'سوازيلاند', 'Eswatini'] },
  { code: 'ls', names: ['ليسوتو', 'Lesotho'] },
  { code: 'ao', names: ['انغولا', 'Angola'] },
  { code: 'er', names: ['إريتريا', 'Eritrea'] },

  // --- AMERICAS OBSCURE ---
  { code: 'bz', names: ['بليز', 'Belize'] },
  { code: 'gt', names: ['غواتيمالا', 'Guatemala'] },
  { code: 'sv', names: ['السلفادور', 'El Salvador'] },
  { code: 'hn', names: ['هندوراس', 'Honduras'] },
  { code: 'ni', names: ['نيكاراغوا', 'Nicaragua'] },
  { code: 'gy', names: ['غويانا', 'Guyana'] },
  { code: 'sr', names: ['سورينام', 'Suriname'] },
  { code: 'bs', names: ['البهاما', 'Bahamas'] },
  { code: 'ht', names: ['هايتي', 'Haiti'] },
  { code: 'do', names: ['الدومينيكان', 'Dominican Republic'] },
  { code: 'kn', names: ['سانت كيتس', 'Saint Kitts'] },
  { code: 'ag', names: ['انتيغوا', 'Antigua'] },
  { code: 'dm', names: ['دومينيكا', 'Dominica'] },
  { code: 'lc', names: ['سانت لوسيا', 'Saint Lucia'] },
  { code: 'bb', names: ['باربادوس', 'Barbados'] },
  { code: 'vc', names: ['سانت فنسنت', 'Saint Vincent'] },
  { code: 'gd', names: ['غرينادا', 'Grenada'] },
  { code: 'tt', names: ['ترينيداد', 'Trinidad'] },
];

export const GRID_DATA = {
  rows: 8,
  cols: 8,
  treasureCount: 10,
  bombCount: 5
};

export const AUCTION_ITEMS = [
  { icon: '💎', name: 'ياقوتة حمراء نادرة', value: 'تقدر بـ 10,000 قطعة' },
  { icon: '⚔️', name: 'سيف أسطوري', value: 'سيف الملك الضائع' },
  { icon: '👑', name: 'تاج الإمبراطور', value: 'مرصع بالألماس' },
  { icon: '🏺', name: 'جرة أثرية', value: 'من عهد الفراعنة' },
];

export const TOURNAMENT_GAMES_LIST = [
  { id: 'GAME_TRIVIA', label: 'مسابقة المعلومات' },
  { id: 'GAME_BLUR', label: 'تخمين الصورة' },
  { id: 'GAME_FLAGS', label: 'تحدي الأعلام' },
  { id: 'GAME_MASAQIL', label: 'حرب المصاقيل' },
  { id: 'GAME_TYPING', label: 'سباق الكتابة' },
  { id: 'GAME_CUPS', label: 'تحدي الأكواب' },
  { id: 'GAME_GRID', label: 'البحث في الشبكة' },
  { id: 'GAME_WHEEL', label: 'عجلة الحظ' },
  { id: 'GAME_PAINT', label: 'حرب الألوان' },
  { id: 'GAME_BATTLE', label: 'حرب الفرق' },
  { id: 'GAME_BOMB', label: 'الكلمة القنبلة' },
];

export const TYPING_WORDS = [
  'أسد', 'نمر', 'فهد', 'قطة', 'كلب', 'ذئب', 'ثعلب', 'دب', 'فيل', 'زرافة',
  'غزال', 'حصان', 'حمار', 'جمل', 'بقرة', 'خروف', 'ماعز', 'أرنب', 'فأر', 'سنجاب',
  'قرد', 'غوريلا', 'شمبانزي', 'كنغر', 'كوالا', 'باندا', 'راكون', 'ظربان', 'قندس', 'مدرع',
  'خفاش', 'حوت', 'دلفين', 'قرش', 'أخطبوط', 'حبار', 'قنديل', 'نجم', 'سرطان', 'جمبري',
  'سمكة', 'تمساح', 'سلحفاة', 'ثعبان', 'أفعى', 'كوبرا', 'سحلية', 'ضب', 'حرباء', 'ضفدع',
  'نسر', 'صقر', 'عقاب', 'بومة', 'غراب', 'عصفور', 'بلبل', 'كناري', 'ببغاء', 'هدهد',
  'نقار', 'نعامة', 'طاووس', 'ديك', 'دجاجة', 'بطة', 'وزة', 'بجعة', 'لقلق', 'نحلة',
  'دبور', 'نملة', 'صرصور', 'ذبابة', 'بعوضة', 'فراشة', 'جندب', 'جرادة', 'خفساء', 'عنكبوت',
  'عقرب', 'دودة', 'حلزون', 'محار', 'لؤلؤ', 'مرجان', 'اسفنج', 'طحالب', 'فطر', 'نبات',
  'شجرة', 'نخلة', 'زهرة', 'وردة', 'ياسمين', 'فل', 'نرجس', 'سوسن', 'بنفسج', 'قرنفل',
  'اقحوان', 'زعفران', 'بابونج', 'نعناع', 'ريحان', 'زعتر', 'بقدونس', 'كزبرة', 'شبت', 'جرجير',
  'خس', 'خيار', 'طماطم', 'بطاطس', 'بصل', 'ثوم', 'فلفل', 'باذنجان', 'كوسة', 'جزر',
  'لفت', 'فجل', 'بنجر', 'سبانخ', 'ملوخية', 'بامية', 'فاصوليا', 'بازلاء', 'عدس', 'فول',
  'حمص', 'ترمس', 'ذرة', 'قمح', 'شعير', 'أرز', 'مكرونة', 'خبز', 'كعك', 'بسكويت',
  'فطيرة', 'بيتزا', 'برجر', 'شاورما', 'كبسة', 'مندي', 'برياني', 'مقلوبة', 'مسقعة', 'محشي',
  'شوربة', 'سلطة', 'مقبلات', 'حلويات', 'كنافة', 'بسبوسة', 'بقلاوة', 'قطايف', 'تمر', 'عجوة',
  'عسل', 'سكر', 'ملح', 'فلفل', 'كمون', 'كركم', 'قرفة', 'زنجبيل', 'هيل', 'قرنفل',
  'قهوة', 'شاي', 'عصير', 'ماء', 'حليب', 'لبن', 'زبدة', 'جبن', 'قشطة', 'بيض',
  'لحم', 'دجاج', 'سمك', 'روبيان', 'تونا', 'سردين', 'فاكهة', 'تفاح', 'برتقال', 'موز',
  'عنب', 'توت', 'فراولة', 'كرز', 'خوخ', 'مشمش', 'برقوق', 'مانجو', 'جوافة', 'رمان',
  'تين', 'زيتون', 'بطيخ', 'شمام', 'يقطين', 'اناناس', 'كيوي', 'ليمون', 'يوسفي', 'جريب',
  'أحمر', 'أخضر', 'أزرق', 'أصفر', 'أبيض', 'أسود', 'رمادي', 'بني', 'برتقالي', 'بنفسجي',
  'وردي', 'ذهبي', 'فضي', 'نحاسي', 'برونزي', 'فاتح', 'غامق', 'لامع', 'باهت', 'شفاف',
  'سماء', 'أرض', 'شمس', 'قمر', 'نجم', 'كوكب', 'مجرة', 'كون', 'فضاء', 'شهاب',
  'نيزك', 'مذنب', 'سحاب', 'مطر', 'ثلج', 'برد', 'ندى', 'ضباب', 'غيوم', 'رياح',
  'عاصفة', 'اعصار', 'زلزال', 'بركان', 'فيضان', 'جفاف', 'حرارة', 'برودة', 'رطوبة', 'طقس',
  'مناخ', 'بيئة', 'طبيعة', 'جبل', 'تل', 'هضبة', 'وادي', 'سهل', 'صحراء', 'غابة',
  'بحر', 'محيط', 'نهر', 'بحيرة', 'شلال', 'نبع', 'بير', 'سد', 'ترعة', 'قناة',
  'جزيرة', 'شبه', 'ساحل', 'شاطئ', 'رمال', 'صخر', 'حصى', 'تراب', 'طين', 'وحل',
  'مدينة', 'قرية', 'حي', 'شارع', 'طريق', 'جسر', 'نفق', 'ميدان', 'حديقة', 'منتزه',
  'ملعب', 'نادي', 'مسبح', 'سينما', 'مسرح', 'متحف', 'مكتبة', 'مدرسة', 'جامعة', 'كلية',
  'معهد', 'حضانة', 'روضة', 'مسجد', 'كنيسة', 'معبد', 'قصر', 'قلعة', 'حصن', 'برج',
  'عمارة', 'منزل', 'بيت', 'شقة', 'غرفة', 'صالة', 'مطبخ', 'حمام', 'شرفة', 'سطح',
  'باب', 'شباك', 'جدار', 'سقف', 'أرضية', 'عمود', 'سلم', 'مصعد', 'أثاث', 'كرسي',
  'طاولة', 'كنبة', 'سرير', 'دولاب', 'رف', 'مرآة', 'ساعة', 'لوحة', 'ستارة', 'سجادة',
  'مصباح', 'ثريا', 'تلفاز', 'راديو', 'هاتف', 'حاسوب', 'انترنت', 'برنامج', 'تطبيق', 'موقع',
  'لعبة', 'فيديو', 'صورة', 'كتاب', 'قلم', 'ورقة', 'ممحاة', 'مسطرة', 'حقيبة', 'سبورة',
  'طباشير', 'دفتر', 'ملف', 'دبوس', 'مقص', 'لاصق', 'خيط', 'إبرة', 'قماش', 'ملابس',
  'قميص', 'بنطال', 'فستان', 'تنورة', 'حذاء', 'جورب', 'قبعة', 'وشاح', 'قفاز', 'معطف',
  'نظارة', 'ساعة', 'خاتم', 'قلادة', 'سوار', 'قرط', 'عطر', 'مشط', 'فرشاة', 'صابون',
  'شامبو', 'معجون', 'منشفة', 'منديل', 'دواء', 'علاج', 'طبيب', 'ممرض', 'مريض', 'ألم',
  'صحة', 'عافية', 'قوة', 'ضعف', 'سرعة', 'بطء', 'ذكاء', 'غباء', 'جمال', 'قبح',
  'خير', 'شر', 'حق', 'باطل', 'صدق', 'كذب', 'أمانة', 'خيانة', 'عدل', 'ظلم',
  'حب', 'كره', 'فرح', 'حزن', 'غضب', 'خوف', 'شجاعة', 'جبن', 'كرم', 'بخل',
  'تواضع', 'غرور', 'صبر', 'جزع', 'أمل', 'يأس', 'علم', 'جهل', 'نور', 'ظلام',
  'حياة', 'موت', 'بداية', 'نهاية', 'ماضي', 'حاضر', 'مستقبل', 'وقت', 'زمن', 'ساعة',
  'دقيقة', 'ثانية', 'يوم', 'أسبوع', 'شهر', 'سنة', 'قرن', 'صباح', 'مساء', 'ظهر',
  'عصر', 'مغرب', 'عشاء', 'ليل', 'نهار', 'فجر', 'غروب', 'شروق', 'إنسان', 'رجل',
  'امرأة', 'طفل', 'شاب', 'عجوز', 'أب', 'أم', 'أخ', 'أخت', 'جد', 'جدة',
  'عم', 'عمة', 'خال', 'خالة', 'زوج', 'زوجة', 'ابن', 'ابنة', 'حفيد', 'صديق',
  'جار', 'زميل', 'مدير', 'موظف', 'عامل', 'خادم', 'رئيس', 'ملك', 'أمير', 'وزير',
  'سفير', 'قاضي', 'محامي', 'شرطي', 'جندي', 'طيار', 'سائق', 'طباخ', 'خباز', 'نجار',
  'حداد', 'خياط', 'حلاق', 'جزار', 'بقال', 'تاجر', 'فلاح', 'صياد', 'رسام', 'شاعر',
  'كاتب', 'صحفي', 'مذيع', 'ممثل', 'مغني', 'لاعب', 'مدرب', 'حكم', 'جمهور', 'فريق',
  'فوز', 'خسارة', 'تعادل', 'هدف', 'كرة', 'مرمى', 'صافرة', 'كأس', 'ميدالية', 'جائزة',
  'سيارة', 'شاحنة', 'حافلة', 'قطاس', 'طائرة', 'سفينة', 'قارب', 'دراجة', 'عربة', 'صاروخ',
  'محرك', 'عجلة', 'وقود', 'نفط', 'غاز', 'كهرباء', 'طاقة', 'مصنع', 'شركة', 'سوق',
  'بنك', 'عملة', 'مال', 'ريال', 'دولار', 'يورو', 'ذهب', 'فضة', 'حديد', 'نحاس',
  'خشب', 'زجاج', 'بلاستيك', 'ورق', 'جلد', 'صوف', 'قطن', 'حرير', 'ماء', 'نار',
  'هواء', 'تراب', 'شمال', 'جنوب', 'شرق', 'غرب', 'يمين', 'يسار', 'فوق', 'تحت',
  'أمام', 'خلف', 'داخل', 'خارج', 'قريب', 'بعيد', 'كبير', 'صغير', 'طويل', 'قصير',
  'عريض', 'ضيق', 'ثقيل', 'خفيف', 'حار', 'بارد', 'جديد', 'قديم', 'غالي', 'رخيص',
  'سهل', 'صعب', 'سريع', 'بطيء', 'نظيف', 'قذر', 'جميل', 'قبيح', 'جيد', 'سيء',
  'سعيد', 'حزين', 'غني', 'فقير', 'قوي', 'ضعيف', 'ذكي', 'غبي', 'كسول', 'نشيط',
  'نائم', 'مستيقظ', 'جائع', 'شبعان', 'عطشان', 'مريض', 'سليم', 'حي', 'ميت', 'حر',
  'عبد', 'مفتوح', 'مغلق', 'ممتلئ', 'فارغ', 'كامل', 'ناقص', 'صحيح', 'خطأ', 'مهم',
  'تافه', 'واضح', 'غامض', 'بسيط', 'معقد', 'عام', 'خاص', 'رسمي', 'شعبي', 'محلي',
  'دولي', 'عالمي', 'وطني', 'أجنبي', 'عربي', 'غربي', 'شرقي', 'شمالي', 'جنوبي', 'بحرية',
  'برية', 'جوية', 'عسكرية', 'مدنية', 'سياسية', 'اقتصادية', 'اجتماعية', 'ثقافية', 'دينية', 'علمية',
  'فنية', 'رياضية', 'تاريخية', 'جغرافية', 'هندسية', 'طبية', 'قانونية', 'تجارية', 'صناعية', 'زراعية',
  'سياحية', 'تعليمية', 'تربوية', 'نفسية', 'فلسفية', 'منطقية', 'حسابية', 'لغوية', 'أدبية', 'شعرية',
  'قصصية', 'روائية', 'مسرحية', 'سينمائية', 'موسيقية', 'غنائية', 'لحنية', 'ايقاعية', 'صوتية', 'بصرية',
  'سمعية', 'حسية', 'عقلية', 'روحية', 'جسدية', 'عضوية', 'خلوية', 'ذرية', 'نووية', 'كونية',
  'فلكية', 'أرضية', 'بحرية', 'جوفية', 'سطحية', 'عميقة', 'عالية', 'منخفضة', 'مستوية', 'متعرجة',
  'مستقيمة', 'منحنية', 'دائرية', 'مربعة', 'مثلثة', 'مستطيلة', 'مكعبة', 'هرمية', 'كروية', 'مسطحة',
  'ناعمة', 'خشنة', 'صلبة', 'سائلة', 'غازية', 'مشعة', 'ملونة', 'بيضاء', 'سوداء', 'حمراء',
  'صفراء', 'خضراء', 'زرقاء', 'برتقالية', 'بنفسجية', 'وردية', 'رمادية', 'بنية', 'ذهبية', 'فضية',
  'نحاسية', 'حديدية', 'خشبية', 'زجاجية', 'ورقية', 'جلدية', 'قماشية', 'بلاستيكية', 'مطاطية', 'شمعية',
  'طينية', 'رملية', 'صخرية', 'ثلجية', 'مائية', 'هوائية', 'نارية', 'كهربائية', 'مغناطيسية', 'جاذبية',
  'حرارية', 'ضوئية', 'صوتية', 'حركية', 'كامنة', 'نووية', 'كيميائية', 'حيوية', 'بيئية', 'مناخية',
  'جوية', 'غيمية', 'ممطرة', 'مشمسة', 'غائمة', 'عاصفة', 'ثلجية', 'ضبابية', 'رطبة', 'جافة',
  'حارة', 'باردة', 'دافئة', 'معتدلة', 'قاسية', 'لطيفة', 'هادئة', 'صاخبة', 'مزدحمة', 'خالية',
  'واسعة', 'ضيقة', 'طويلة', 'قصيرة', 'عالية', 'منخفضة', 'سميكة', 'رقيقة', 'رفيعة', 'عريضة',
  'ثقيلة', 'خفيفة', 'سريعة', 'بطيئة', 'قوية', 'ضعيفة', 'جديدة', 'قديمة', 'حديثة', 'تقليدية',
  'أصلية', 'مقلدة', 'نادرة', 'شائعة', 'غريبة', 'مألوفة', 'معروفة', 'مجهولة', 'واضحة', 'غائبة',
  'حاضرة', 'مفقودة', 'موجودة', 'معدومة', 'ممكنة', 'مستحيلة', 'سهلة', 'صعبة', 'بسيطة', 'معقدة',
  'ممتعة', 'مملة', 'مفيدة', 'ضارة', 'نافعة', 'مؤذية', 'آمنة', 'خطيرة', 'سليمة', 'مكسورة',
  'نظيفة', 'متسخة', 'طاهرة', 'نجسة', 'طيبة', 'خبيثة', 'صالحة', 'فاسدة', 'حلال', 'حرام',
  'مباح', 'مكروه', 'مستحب', 'واجب', 'فرض', 'سنة', 'نافلة', 'عبادة', 'طاعة', 'معصية',
  'توبة', 'استغفار', 'دعاء', 'ذكر', 'صلاة', 'زكاة', 'صوم', 'حج', 'عمرة', 'جهاد',
  'إيمان', 'إسلام', 'إحسان', 'تقوى', 'ورع', 'زهد', 'يقين', 'توكل', 'رضا', 'شكر',
  'حمد', 'تسبيح', 'تهليل', 'تكبير', 'صبر', 'حلم', 'أناة', 'رفق', 'لين', 'عطف',
  'حنان', 'رحمة', 'مودة', 'ألفة', 'محبة', 'عشق', 'غرام', 'هيام', 'شوق', 'حنين',
  'لهفة', 'رغبة', 'رهبة', 'خوف', 'رجاء', 'أمل', 'طموح', 'هدف', 'غاية', 'وسيلة',
  'طريقة', 'أسلوب', 'منهج', 'خطة', 'نظام', 'ترتيب', 'تنظيم', 'تنسيق', 'ادارة', 'قيادة',
  'رئاسة', 'زعامة', 'سيادة', 'سلطة', 'حكم', 'قرار', 'أمر', 'نهي', 'قانون', 'دستور',
  'لائحة', 'قاعدة', 'مبدأ', 'عقيدة', 'فكرة', 'رأي', 'وجهة', 'نظر', 'قول', 'فعل',
  'عمل', 'شغل', 'وظيفة', 'مهنة', 'حرفة', 'صنعة', 'مهمة', 'واجب', 'مسؤولية', 'التزام',
  'عهد', 'وعد', 'ميثاق', 'عقد', 'اتفاق', 'صفقة', 'بيعة', 'شراء', 'بيع', 'إيجار',
  'استثمار', 'تمويل', 'قرض', 'دين', 'سداد', 'ربح', 'خسارة', 'فائدة', 'رأس', 'مال',
  'ثروة', 'غنى', 'فقر', 'حاجة', 'عوز', 'نقص', 'زيادة', 'نمو', 'تطور', 'تقدم',
  'تأخر', 'تخلف', 'انحطاط', 'رقي', 'ازدهار', 'حضارة', 'ثقافة', 'تراث', 'تاريخ', 'جغرافيا',
  'فلسفة', 'منطق', 'علم', 'فن', 'أدب', 'شعر', 'نثر', 'قصة', 'رواية', 'مسرح',
  'سينما', 'موسيقى', 'غناء', 'رسم', 'نحت', 'تصوير', 'تمثيل', 'إخراج', 'إنتاج', 'توزيع',
  'نشر', 'إعلام', 'صحافة', 'اذاعة', 'تلفزيون', 'انترنت', 'تواصل', 'اتصال', 'حوار', 'نقاش',
  'جدال', 'خلاف', 'صراع', 'نزاع', 'حرب', 'سلام', 'أمن', 'أمان', 'استقرار', 'فوضى',
  'شغب', 'عنف', 'ارهاب', 'جريمة', 'سرقة', 'قتل', 'ضرب', 'جرح', 'دم', 'ألم',
  'مرض', 'علاج', 'شفاء', 'دواء', 'طبيب', 'مستشفى', 'عيادة', 'صيدلية', 'اسعاف', 'طوارئ',
  'شرطة', 'جيش', 'حرس', 'أمن', 'مخابرات', 'جاسوس', 'عميل', 'خائن', 'وطني', 'شهيد',
  'بطل', 'شجاع', 'جبان', 'قوي', 'ضعيف', 'منتصر', 'مهزوم', 'أسير', 'حر', 'سجين',
  'سجن', 'زنزانة', 'محكمة', 'قاضي', 'محامي', 'متهم', 'بريء', 'مدان', 'حكم', 'قصاص',
  'عدالة', 'انصاف', 'حق', 'واجب', 'حرية', 'مسؤولية', 'ديمقراطية', 'ديكتاتورية', 'ملكية', 'جمهورية',
  'انتخابات', 'تصويت', 'برلمان', 'حكومة', 'وزارة', 'سفارة', 'قنصلية', 'جواز', 'تأشيرة', 'سفر',
  'سياحة', 'رحلة', 'اجازة', 'عطلة', 'عمل', 'دراسة', 'بعثة', 'منحة', 'شهادة', 'جائزة',
  'مكافأة', 'راتب', 'دخل', 'مصروف', 'تكلفة', 'سعر', 'قيمة', 'جودة', 'كمية', 'عدد',
  'رقم', 'حساب', 'رياضيات', 'فيزياء', 'كيمياء', 'أحياء', 'جيولوجيا', 'فلك', 'طب', 'هندسة',
  'زراعة', 'صناعة', 'تجارة', 'اقتصاد', 'سياسة', 'اجتماع', 'نفس', 'تربية', 'تعليم', 'تدريب',
  'مهارة', 'خبرة', 'معرفة', 'معلومة', 'بيانات', 'تحليل', 'بحث', 'دراسة', 'تجربة', 'اختبار',
  'امتحان', 'سؤال', 'جواب', 'حل', 'مشكلة', 'أزمة', 'كارثة', 'مصيبة', 'بلاء', 'نعمة',
  'فضل', 'هبة', 'هدية', 'عطية', 'منحة', 'مساعدة', 'عون', 'دعم', 'تشجيع', 'تحفيز',
  'الهام', 'ابداع', 'ابتكار', 'اختراع', 'اكتشاف', 'انجاز', 'نجاح', 'فشل', 'خطأ', 'صواب',
  'رأي', 'فكر', 'عقل', 'قلب', 'روح', 'نفس', 'جسد', 'بدن', 'رأس', 'وجه',
  'عين', 'أذن', 'أنف', 'فم', 'لسان', 'سن', 'شعر', 'يد', 'رجل', 'قدم',
  'بطن', 'ظهر', 'صدر', 'قلب', 'كبد', 'كلية', 'رئة', 'معدة', 'أمعاء', 'دم',
  'عظم', 'لحم', 'جلد', 'عصب', 'مخ', 'عضلات', 'مفاصل', 'شرايين', 'أوردة', 'خلايا',
  'أنسجة', 'أعضاء', 'حواس', 'بصر', 'سمع', 'شم', 'ذوق', 'لمس', 'حركة', 'سكون',
  'نوم', 'يقظة', 'حلم', 'خيال', 'واقع', 'حقيقة', 'زيف', 'وهم', 'شك', 'يقين'
];

export const BOMB_SYLLABLES = [
  'با', 'را', 'سي', 'لو', 'ما', 'نا', 'كي', 'تو', 'في', 'جا'
];

export const ZOMBIE_OBSTACLES = [
  { question: 'ما هو حاصل ضرب 5 في 6؟', answer: '30' },
  { question: 'عاصمة السعودية؟', answer: 'الرياض' },
  { question: 'أكبر كوكب في المجموعة الشمسية؟', answer: 'المشتري' },
  { question: 'كم عدد أركان الإسلام؟', answer: '5' },
];